'use client';

/**
 * OptimizedImage (slice, M12) — modern-format image delivery under the static
 * export, where Next's runtime optimizer is unavailable (`images:{unoptimized:true}`
 * ). It serves build-time derivatives (AVIF/WebP, generated by
 * `scripts/gen-images.mjs` and recorded in `lib/image-manifest.json`) through a
 * native <picture>, with the original raster as the universal fallback.
 *
 * Contract it preserves
 * basePath-safe: EVERY emitted path (avif/webp srcSet and the <img> src) is wrapped
 * in withBasePath, so it works on the default build AND the
 * NEXT_PUBLIC_BASE_PATH=/trip_planner build. withBasePath is the sole basePath source.
 * onError fallback: if the raster fails (or the basePath is wrong), `onError` fires
 * and we render the caller-provided `fallback` (the pre-existing gradient/emoji/icon
 * design), keeping the zero-broken-images bar. A <source> can't signal load failure
 * so the universal <img> fallback is what the browser ultimately decodes and what
 * triggers onError — the AVIF/WebP <source>s only ever win when they actually decode.
 *
 * CLS: explicit width/height (intrinsic, from the manifest) reserve the box before
 * load → layout shift ≈ 0. Callers that lay the image out with `fill`-style absolute
 * positioning pass `fill` and we stretch to the positioned parent (the parent already
 * reserves the box via aspect-ratio), still emitting width/height for the intrinsic
 * ratio.
 *
 * LCP: `priority` images load eager + fetchPriority="high" and are NOT lazy (the hero).
 * Everything else is `loading="lazy"`.
 *
 * Reduced-motion: the blur-up is a pure opacity swap on load; under
 * `prefers-reduced-motion: reduce` the transition is neutralized (the global CSS guard
 * in globals.css zeroes transition-duration app-wide) and we additionally start at
 * full opacity so there is no perceptible fade — the final raster simply shows.
 *
 * Graceful when unmapped: if `src` is absent from the manifest (e.g. a brand-new asset
 * not yet processed) we render a plain basePath-safe <img> with the same onError, so the
 * component never hard-depends on the manifest being complete.
 */

import { useEffect, useRef, useState, type ReactNode } from 'react';
import { withBasePath } from '@/lib/utils';
import manifest from '@/lib/image-manifest.json';

type ImageManifestEntry = {
  webp: string;
  avif: string;
  blurDataURL: string;
  width: number;
  height: number;
};

const IMAGE_MANIFEST = manifest as Record<string, ImageManifestEntry>;

export interface OptimizedImageProps {
  /** Root-relative source path, e.g. "/images/nepal/na1.jpg" — the manifest key. */
  src: string;
  /** Required alt text. Pass "" for purely decorative images (e.g. the hero). */
  alt: string;
  /** Intrinsic width override; defaults to the manifest value. */
  width?: number;
  /** Intrinsic height override; defaults to the manifest value. */
  height?: number;
  /** `sizes` attribute for responsive selection. */
  sizes?: string;
  /** LCP image: eager + fetchPriority="high", never lazy. Default false → lazy. */
  priority?: boolean;
  /** className applied to the rendered <img>. */
  className?: string;
  /**
   * Stretch to a positioned parent (parent must be `relative` and reserve the box
   * typically via an aspect-ratio utility). Mirrors next/image `fill` ergonomics so
   * existing `fill` call sites convert with no layout change.
   */
  fill?: boolean;
  /**
   * Rendered in place of the image when the raster fails to load (mandatory
   * fallback). When omitted, the component renders nothing on error (the caller's own
   * conditional/sibling art shows through).
   */
  fallback?: ReactNode;
  /**
   * Called when the raster fails to load, in addition to rendering `fallback`. Lets a
   * caller that already drives its own gradient/emoji fallback via state (the existing
   * pattern) hook the same `setImgError(true)` it used with next/image, so the
   * wiring change stays localized to the image element.
   */
  onError?: () => void;
  /** Forwarded to the underlying <img> (e.g. `draggable`). */
  imgProps?: React.ImgHTMLAttributes<HTMLImageElement>;
}

export default function OptimizedImage({
  src,
  alt,
  width,
  height,
  sizes,
  priority = false,
  className,
  fill = false,
  fallback = null,
  onError,
  imgProps,
}: OptimizedImageProps) {
  const entry = IMAGE_MANIFEST[src];
  const [errored, setErrored] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const imgRef = useRef<HTMLImageElement | null>(null);

  const resolvedWidth = width ?? entry?.width;
  const resolvedHeight = height ?? entry?.height;

  // A cached image can finish loading before React attaches `onLoad`. Reconcile from
  // the DOM after mount so the blur-up never gets stuck at 0 opacity.
  useEffect(() => {
    if (imgRef.current?.complete && imgRef.current.naturalWidth > 0) {
      setLoaded(true);
    }
  }, []);

  if (errored) {
    return <>{fallback}</>;
  }

  // Blur-up backdrop: the LQIP sits behind the image and the image fades in over it.
  // Pure opacity (no transform) so it's reduced-motion-safe; the global CSS guard
  // zeroes the transition under prefers-reduced-motion.
  const blur = entry?.blurDataURL;

  const baseImgStyle: React.CSSProperties = fill
    ? { position: 'absolute', inset: 0, width: '100%', height: '100%' }
    : {};

  const imgStyle: React.CSSProperties = {
    ...baseImgStyle,
    opacity: loaded ? 1 : 0,
    transition: 'opacity 400ms ease',
    ...(imgProps?.style ?? {}),
  };

  // React 18's ImgHTMLAttributes type predates `fetchPriority`; emit the real
  // lowercase HTML attribute (`fetchpriority="high"`) the browser uses to prioritize
  // the LCP image, via a typed extra-attrs object so tsc stays clean.
  const priorityAttrs = (priority ? { fetchpriority: 'high' } : {}) as Record<string, string>;

  const imgEl = (
    <img
      ref={imgRef}
      src={withBasePath(src)}
      alt={alt}
      width={resolvedWidth}
      height={resolvedHeight}
      sizes={sizes}
      loading={priority ? 'eager' : 'lazy'}
      decoding="async"
      className={className}
      style={imgStyle}
      onLoad={() => setLoaded(true)}
      onError={() => {
        setErrored(true);
        onError?.();
      }}
      {...priorityAttrs}
      {...imgProps}
    />
  );

  // No manifest entry → plain basePath-safe <img> with the same onError (graceful).
  if (!entry) {
    return imgEl;
  }

  return (
    <>
      {/* LQIP backdrop — fades OUT as the real image fades in. aria-hidden; decorative. */}
      {blur && (
        <img
          src={blur}
          alt=""
          aria-hidden="true"
          className={className}
          style={{
            ...(fill ? { position: 'absolute', inset: 0, width: '100%', height: '100%' } : {}),
            opacity: loaded ? 0 : 1,
            transition: 'opacity 400ms ease',
            // Blur the tiny LQIP so its low resolution reads as a soft placeholder.
            filter: 'blur(12px)',
            transform: 'scale(1.05)',
          }}
        />
      )}
      <picture>
        <source type="image/avif" srcSet={withBasePath(entry.avif)} sizes={sizes} />
        <source type="image/webp" srcSet={withBasePath(entry.webp)} sizes={sizes} />
        {imgEl}
      </picture>
    </>
  );
}
