/**
 * `core/content/registry.ts` — `contentRef` → `TripContent` resolution (v5 Phase-1
 *;). Framework-free: plain TS, no React/Next/`window`. Static-import registry
 * — one pack today; code-splitting a hypothetical second pack is a future concern, not now.
 *
 * `TripContent.legs` is keyed by `TripLeg.contentKey` ('nepal' | 'japan' for the default pack —
 * see `core/trips/packs/nepal-japan-2026.ts`). `LegContent` mirrors EXACTLY what
 * `lib/nepal-data.ts` / `lib/japan-data.ts` already exported before this slice (attractions +
 * food + the category filter list) — this is an indirection slice, not a content redesign.
 *
 * The literal guide data used to live directly in `lib/nepal-data.ts` / `lib/japan-data.ts`;
 * it now lives HERE (byte-identical values) and those two `lib/` files become thin re-export
 * facades over this registry's default-pack entry ( facade pattern, same as
 * `lib/trip-data.ts` over `core/dates`) — same exported names, same values, so every existing
 * consumer (components, hooks, tests) is untouched.
 *
 * Import arrow: this file imports the `Recommendation` TYPE ONLY from `lib/nepal-data.ts`
 * (erased at compile time — no runtime cycle) because `lib/nepal-data.ts` re-exports this
 * file's VALUES. `core/content` still imports nothing from `core/dates` / `core/trips`
 *.
 */
import type { Recommendation } from '@/lib/nepal-data';
import type { DayPlan } from '@/lib/trip-data';
import { TRIP_ITINERARY } from './itinerary';

// ── Nepal guide content (moved byte-identically from the former lib/nepal-data.ts) ──────────

export const NEPAL_ATTRACTIONS: Recommendation[] = [
  // --- Temples & Cultural Sites ---
  { id: 'na1', image: '/images/nepal/na1.jpg', name: 'Boudhanath Stupa', category: 'Temple', description: 'One of the largest spherical stupas in Nepal, a UNESCO World Heritage Site. The mandala-design dome is surrounded by prayer wheels and monasteries.', bestTime: 'Early morning or sunset', duration: '2-3 hours', photoRating: 5, notes: 'Walk clockwise around the stupa. Best light at golden hour.', location: 'Boudha, Kathmandu', mustSee: true, longDescription: 'Boudhanath is one of the largest stupas in the world and the centre of Tibetan Buddhism in Nepal. The colossal white dome, topped by a gilded tower painted with the all-seeing eyes of the Buddha, was rebuilt after the 2015 earthquake. It sits at the heart of a bustling neighbourhood of monasteries (gompas), thangka workshops and rooftop cafes, and comes alive at dusk when pilgrims circle it clockwise spinning prayer wheels and lighting butter lamps.' },
  { id: 'na2', image: '/images/nepal/na2.jpg', name: 'Swayambhunath (Monkey Temple)', category: 'Temple', description: 'Ancient religious complex atop a hill with panoramic views of Kathmandu Valley. Watch playful monkeys and explore Buddhist and Hindu shrines.', bestTime: 'Sunrise', duration: '2 hours', photoRating: 5, notes: '365 steps to the top. Bring wide-angle lens for cityscape.', location: 'Swayambhu Hill', mustSee: true, longDescription: 'Perched on a hilltop west of the city, Swayambhunath is one of the oldest religious sites in Nepal, its central stupa crowned by the painted eyes of the Buddha gazing in four directions. A steep flight of 365 stone steps lined with prayer flags and resident rhesus macaques (hence "Monkey Temple") climbs to a complex where Buddhist and Hindu shrines mingle. The summit offers one of the best panoramas of the Kathmandu Valley, especially at first light.' },
  { id: 'na3', image: '/images/nepal/na3.jpg', name: 'Pashupatinath Temple', category: 'Temple', description: 'Sacred Hindu temple on the banks of the Bagmati River. Witness cremation ceremonies and the evening aarti ritual.', bestTime: 'Morning or evening aarti', duration: '2-3 hours', photoRating: 4, notes: 'Non-Hindus cannot enter main temple. Cremation photography requires sensitivity.', location: 'Pashupatinath', mustSee: true, longDescription: 'Pashupatinath is Nepal\'s most sacred Hindu temple complex, a sprawling UNESCO-listed site on the banks of the holy Bagmati River dedicated to Lord Shiva. Non-Hindus cannot enter the golden-roofed main temple but can watch openly from the opposite bank, where riverside ghats host public cremations and, each evening, a mesmerising Bagmati aarti of fire, chanting and bells. Sadhus (holy men) in ochre robes and ash gather in the surrounding courtyards.' },
  { id: 'na11', image: '/images/nepal/na11.jpg', name: 'Budhanilkantha Temple', category: 'Temple', description: 'Home to Nepal\'s largest stone statue of the reclining Vishnu, carved from a single block of black basalt and floating in a recessed water tank.', bestTime: 'Early morning', duration: '1-2 hours', photoRating: 4, notes: 'The 5-metre sleeping Vishnu dates to the 7th century. Quiet and uncrowded at dawn.', location: 'Budhanilkantha, north Kathmandu' },
  { id: 'na12', image: '/images/nepal/na12.jpg', name: 'Changu Narayan Temple', category: 'Temple', description: 'The oldest Hindu temple in the Kathmandu Valley and a UNESCO site, famed for exquisite 5th-century stone, wood and metal craftsmanship.', bestTime: 'Morning', duration: '2 hours', photoRating: 5, notes: 'Pair with a short hike down to Bhaktapur or Nagarkot. Newari woodcarving at its finest.', location: 'Changunarayan hill' },

  // --- Must-Visit (Durbar Squares) ---
  { id: 'na4', image: '/images/nepal/na4.jpg', name: 'Kathmandu Durbar Square', category: 'Must-Visit', description: 'Historic royal palace square with temples, courtyards, and the living goddess Kumari. A UNESCO site showcasing Newari architecture.', bestTime: 'Morning', duration: '3 hours', photoRating: 5, notes: 'Visit Kumari Ghar to see the living goddess. Entry fee for foreigners.', location: 'Basantapur', mustSee: true, longDescription: 'The old royal square at the heart of Kathmandu (also called Hanuman Dhoka) is a UNESCO World Heritage Site packed with pagoda temples, courtyards and the former royal palace, all in intricate Newari brick-and-timber style. It is home to the Kumari Ghar, residence of the living goddess who occasionally appears at a carved window. Some structures were lost in the 2015 earthquake and restoration continues, but the square remains a living centre of ritual and daily life.' },
  { id: 'na5', image: '/images/nepal/na5.jpg', name: 'Patan Durbar Square', category: 'Must-Visit', description: 'A dense collection of Newari architecture. Krishna Temple, the Golden Temple, and the Patan Museum ring the square.', bestTime: 'Morning to afternoon', duration: '3-4 hours', photoRating: 5, notes: 'The Patan Museum is well worth the time. Explore surrounding alleys for hidden courtyards.', location: 'Lalitpur', mustSee: true, longDescription: 'Across the Bagmati in the city of Lalitpur, Patan Durbar Square is often considered the finest concentration of Newari architecture in the valley. Highlights include the stone Krishna Mandir carved from a single shikhara-style block, the gilded Golden Temple (Hiranya Varna Mahavihar), and the acclaimed Patan Museum housed in a restored palace wing. The surrounding lanes of Patan hide countless Buddhist courtyards (bahals) and metalworking workshops.' },
  { id: 'na6', image: '/images/nepal/na6.jpg', name: 'Bhaktapur Durbar Square', category: 'Must-Visit', description: 'Best preserved medieval city in the Kathmandu Valley. 55-Window Palace, Nyatapola Temple, and traditional pottery squares.', bestTime: 'Full day visit', duration: '5-6 hours', photoRating: 5, notes: 'Try the famous Juju Dhau (King Curd). Least touristy of the three squares.', mustSee: true, longDescription: 'Bhaktapur is the best-preserved medieval town in the Kathmandu Valley, a UNESCO site where car-free brick lanes open onto three linked squares. The Durbar Square holds the 55-Window Palace and the Golden Gate; nearby Taumadhi Square is dominated by the five-tiered Nyatapola, Nepal\'s tallest pagoda, while Pottery Square is still lined with potters spinning clay in the open air. It is famous for its creamy Juju Dhau ("king curd").' },

  // --- Hidden Gems ---
  { id: 'na7', image: '/images/nepal/na7.jpg', name: 'Garden of Dreams', category: 'Hidden Gem', description: 'A neo-classical garden oasis in the heart of Kathmandu. Fountains, pergolas, and peaceful pavilions away from city chaos.', bestTime: 'Afternoon', duration: '1-2 hours', photoRating: 4, notes: 'Perfect escape from bustling Thamel. Small entry fee.', location: 'Keshar Mahal, Kathmandu', longDescription: 'A restored 1920s neo-classical garden built by a Rana general, the Garden of Dreams is a walled Edwardian oasis of pavilions, pergolas, fountains and a lily pond right beside Thamel. Beautifully renovated with Austrian support, it is a favourite spot to escape the noise of the city with a coffee at the Kaiser Cafe. It sits directly next to the Tulsi Kathmandu Hotel area.' },
  { id: 'na8', image: '/images/nepal/na8.jpg', name: 'Asan Bazaar', category: 'Hidden Gem', description: 'The oldest and most vibrant market in Kathmandu. Spices, vegetables, fabrics, and hidden temples in narrow alleyways.', bestTime: 'Morning', duration: '2 hours', photoRating: 5, notes: 'Best street photography spot in KTM. Follow the ancient trade route.', location: 'Asan, Kathmandu', longDescription: 'Asan is the oldest and busiest bazaar in Kathmandu, a six-way junction on the historic trade route to Tibet. Its dense lanes overflow with vendors selling spices, grains, textiles, brass and fresh produce, and the small Annapurna and Ganesh temples at its centre are still active. Go in the morning for the most energetic scenes — it is widely regarded as the best street-photography spot in the city.' },
  { id: 'na13', image: '/images/nepal/na13.jpg', name: 'Pharping & Asura Cave', category: 'Hidden Gem', description: 'A serene cluster of Buddhist monasteries and the sacred Asura Cave where Guru Rinpoche meditated, set in pine-forested hills south of the valley.', bestTime: 'Morning', duration: 'Half day', photoRating: 4, notes: 'Combine with the Dakshinkali temple nearby. Peaceful and rarely crowded.', location: 'Pharping' },

  // --- Nature ---
  { id: 'na9', image: '/images/nepal/na9.jpg', name: 'Shivapuri National Park', category: 'Nature', description: 'Lush forested national park on the valley\'s northern rim with hiking trails, waterfalls and the Bagmati river source. Rich birdlife and mountain air.', bestTime: 'Morning', duration: 'Half to full day', photoRating: 4, notes: 'Trailhead near Budhanilkantha. Good for a half-day forest hike.', location: 'Shivapuri-Nagarjun' },
  { id: 'na10', image: '/images/nepal/na10.jpg', name: 'Taudaha Lake', category: 'Nature', description: 'A tranquil natural lake on the valley\'s southern edge, a winter stopover for migratory birds and a calm spot for a quiet walk away from the city.', bestTime: 'Late afternoon', duration: '1-2 hours', photoRating: 3, notes: 'Best birdwatching in December. Tea stalls along the shore.', location: 'Chobhar' },

  // --- Photography Locations ---
  { id: 'na14', image: '/images/nepal/na14.jpg', name: 'Chobhar Gorge', category: 'Photography', description: 'A dramatic river gorge where the Bagmati cuts through the valley rim, with the Jal Binayak temple and a vintage suspension bridge framing the water.', bestTime: 'Late afternoon', duration: '1-2 hours', photoRating: 4, notes: 'Wide-angle for the gorge, telephoto for temple detail. Soft side light after 3 PM.', location: 'Chobhar' },
  { id: 'na15', image: '/images/nepal/na15.jpg', name: 'Kopan Monastery Viewpoint', category: 'Photography', description: 'A hilltop Buddhist monastery overlooking Boudhanath and the valley, with prayer flags, golden roofs and sweeping skyline compositions.', bestTime: 'Sunset', duration: '1-2 hours', photoRating: 5, notes: 'Frame Boudhanath stupa against the city below at dusk. Respect monastery quiet hours.', location: 'Kopan hill, Boudha' },
  { id: 'na16', image: '/images/nepal/na16.jpg', name: 'Sarangkot-style Valley Rim at Phulchowki', category: 'Photography', description: 'The valley\'s highest rim peak, blanketed in rhododendron forest, offering layered ridge-line and Himalayan panorama shots on clear winter mornings.', bestTime: 'Pre-dawn to early morning', duration: 'Half day', photoRating: 5, notes: 'Clearest December skies reveal distant peaks. Bring a telephoto for compressed ridges.', location: 'Phulchowki, Godavari' },

  // --- Day Trips ---
  { id: 'na17', image: '/images/nepal/na17.jpg', name: 'Nagarkot Sunrise', category: 'Day Trip', description: 'Famous hilltop viewpoint offering panoramic sunrise views over the Himalayan range including Everest, Langtang and Ganesh Himal.', bestTime: 'Pre-dawn to sunrise', duration: 'Half day', photoRating: 5, notes: 'Leave Kathmandu by 4:30 AM. Bring tripod and telephoto lens.', location: 'Nagarkot', mustSee: true, longDescription: 'Nagarkot is a ridge-top village about 30 km east of Kathmandu, famed for its sweeping Himalayan horizon. On clear winter mornings the sunrise reveals a long arc of peaks — including the Langtang, Ganesh Himal and Rolwaling ranges, and on the clearest days a distant glimpse of Everest. December offers some of the year\'s best visibility. Stay overnight or leave the city very early to catch first light from a viewpoint tower.' },
  { id: 'na18', image: '/images/nepal/na18.jpg', name: 'Chandragiri Hills Cable Car', category: 'Day Trip', description: 'Cable car ride to a hilltop with stunning views of the Himalayas and Kathmandu Valley. Clear winter days offer Everest views.', bestTime: 'Clear morning', duration: '3-4 hours', photoRating: 5, notes: 'December offers clearest mountain views. Bring layers for cold at the top.', location: 'Chandragiri' },
  { id: 'na19', image: '/images/nepal/na19.jpg', name: 'Dhulikhel', category: 'Day Trip', description: 'A historic Newari town on the valley\'s eastern edge with cobbled streets, traditional architecture and a renowned wraparound Himalayan panorama.', bestTime: 'Sunrise or sunset', duration: 'Full day', photoRating: 5, notes: 'About 30 km from Kathmandu. Walk the ridge to the Kali shrine viewpoint.', location: 'Dhulikhel, Kavre' },
  { id: 'na20', image: '/images/nepal/na20.jpg', name: 'Namo Buddha', category: 'Day Trip', description: 'One of Tibetan Buddhism\'s holiest sites, home to the Thrangu Tashi Yangtse Monastery set among terraced hills and forest stupas.', bestTime: 'Morning', duration: 'Full day', photoRating: 4, notes: 'Pair with Dhulikhel and Panauti for a scenic loop. Vegetarian meals at the monastery.', location: 'Namobuddha, Kavre' },
];

export const NEPAL_FOOD: Recommendation[] = [
  { id: 'nf1', image: '/images/nepal/nf1.jpeg', name: 'Bhojan Griha', category: 'Food', description: 'Traditional Nepali feast in a 150-year-old heritage building with cultural performances. Multi-course dal bhat dinner.', bestTime: 'Dinner', duration: '2 hours', photoRating: 4, notes: 'Reservation recommended. Cultural dance show included.', location: 'Dillibazar, Kathmandu', longDescription: 'Set in a lovingly restored 19th-century Rana-era mansion in Dillibazar, Bhojan Griha serves a multi-course traditional Nepali feast (a fixed set menu of dal bhat, curries, pickles and sweets) accompanied by live folk music and dance performances. It is a popular, atmospheric introduction to Newari and hill-Nepali cuisine — reservations are recommended, especially in the evening.' },
  { id: 'nf2', image: '/images/nepal/nf2.jpg', name: 'Yangling Restaurant', category: 'Food', description: 'Legendary momo spot in Thamel. Steamed, fried, and jhol momos with authentic Tibetan-Nepali flavors.', bestTime: 'Lunch', duration: '1 hour', photoRating: 3, notes: 'Try the jhol (soup) momos. Simple atmosphere, incredible food.' },
  { id: 'nf3', image: '/images/nepal/nf3.jpg', name: 'OR2K Restaurant', category: 'Café', description: 'Mediterranean-Nepali fusion with stunning rooftop views. Cushion seating, hookah-friendly, great hummus and falafel.', bestTime: 'Breakfast or sunset', duration: '1.5 hours', photoRating: 4, notes: 'Rooftop sunset views are magical. Vegetarian-friendly.' },
  { id: 'nf4', image: '/images/nepal/nf4.jpg', name: 'Cafe Swotha', category: 'Food', description: 'Newari cuisine served in a beautifully restored heritage courtyard in Patan. Authentic local flavors in elegant setting.', bestTime: 'Lunch', duration: '1.5 hours', photoRating: 4, notes: 'Try the Newari set meal. Beautiful courtyard architecture.' },
  { id: 'nf5', image: '/images/nepal/nf5.jpg', name: 'Roadhouse Cafe', category: 'Café', description: 'Best wood-fired pizza in Kathmandu with craft beer selection. Modern atmosphere, popular with expats.', bestTime: 'Dinner', duration: '1.5 hours', photoRating: 3, notes: 'Multiple locations. Thamel branch has best atmosphere.' },
  { id: 'nf6', image: '/images/nepal/nf6.jpeg', name: 'Thakali Kitchen', category: 'Food', description: 'Authentic Thakali dal bhat - the quintessential Nepali meal. Unlimited refills on rice, dal, vegetables.', bestTime: 'Lunch', duration: '1 hour', photoRating: 3, notes: 'Eat with right hand for authentic experience. Dal bhat power!' },
  { id: 'nf7', image: '/images/nepal/nf7.jpg', name: 'Himalayan Java', category: 'Café', description: 'Nepal\'s premier coffee chain using locally grown beans from the hills. Multiple scenic locations across Kathmandu.', bestTime: 'Morning', duration: '1 hour', photoRating: 3, notes: 'Try Nepali-grown coffee. Garden-view branch near Thamel is best.' },
];

export const NEPAL_CATEGORIES = ['All', 'Must-Visit', 'Hidden Gem', 'Temple', 'Food', 'Café', 'Nature', 'Photography', 'Day Trip'];

// ── Japan guide content (moved byte-identically from the former lib/japan-data.ts) ──────────

export const JAPAN_ATTRACTIONS: Recommendation[] = [
  { id: 'ja1', image: '/images/japan/ja1.jpg', name: 'Senso-ji Temple', category: 'Must-See', description: 'Tokyo\'s oldest and most significant Buddhist temple. The Thunder Gate (Kaminarimon) and Nakamise shopping street are iconic.', bestTime: 'Early morning or night', duration: '2-3 hours', photoRating: 5, notes: 'Visit at dawn for empty shots. Night illumination is magical.', location: 'Asakusa, Tokyo', mustSee: true, longDescription: 'Founded in 645, Senso-ji is Tokyo\'s oldest temple and its most visited. You enter through the towering Kaminarimon ("Thunder Gate") with its giant red lantern, then walk the Nakamise-dori, a centuries-old shopping street of snack and souvenir stalls, up to the main hall and five-storey pagoda. It is free to enter, busy by day and beautifully lit after dark; the Asakusa district around it keeps an old-Tokyo, downtown feel.', priceHint: 'Free (grounds & main hall)' },
  { id: 'ja2', image: '/images/japan/ja2.jpg', name: 'Fushimi Inari Shrine', category: 'Must-See', description: 'Thousands of vermillion torii gates winding up a mountainside. One of the most photographed sites in Japan.', bestTime: 'Dawn or dusk', duration: '2-4 hours', photoRating: 5, notes: 'Go early to avoid crowds. Full hike to summit takes 2-3 hours.', location: 'Kyoto', mustSee: true, longDescription: 'Fushimi Inari Taisha is the head shrine of Inari, the Shinto deity of rice and prosperity, and one of Japan\'s most iconic sights. Thousands of vermilion torii gates — donated by businesses — form tunnels that wind up the wooded slopes of Mt Inari. A full loop to the summit takes two to three hours; most visitors turn back at the Yotsutsuji intersection for the valley view. It is open 24 hours and free, so dawn visits reward you with empty gate tunnels.', priceHint: 'Free · open 24h' },
  { id: 'ja3', image: '/images/japan/ja3.jpg', name: 'Shibuya Crossing', category: 'Must-See', description: 'The world\'s busiest pedestrian crossing. Up to 3,000 people cross simultaneously. An icon of Tokyo\'s urban energy.', bestTime: 'Evening rush hour', duration: '1 hour', photoRating: 5, notes: 'Best viewed from Shibuya Sky observation deck or Starbucks.', location: 'Shibuya, Tokyo', mustSee: true, longDescription: 'Shibuya Scramble Crossing is the emblem of modern Tokyo — when the lights change, waves of pedestrians surge across from all directions at once beneath giant video screens. It is busiest around evening rush hour. For the classic overhead view, head up to the open-air Shibuya Sky observation deck atop Shibuya Scramble Square, or watch from the second-floor Starbucks in the Tsutaya building. The loyal-dog Hachiko statue stands just outside the station.' },
  { id: 'ja4', image: '/images/japan/ja4.jpg', name: 'Tokyo Tower', category: 'Must-See', description: 'A 333m communications tower with observation decks looking out over the city, especially good at night.', bestTime: 'Sunset to night', duration: '1.5 hours', photoRating: 5, notes: 'Winter nights offer the clearest views. Top deck worth the extra fee.', location: 'Minato, Tokyo', longDescription: 'Completed in 1958 and modelled on the Eiffel Tower, the 333-metre Tokyo Tower remains a beloved city landmark, painted white and international orange. It has a Main Deck at 150 m and a higher Top Deck at 250 m reached by a guided tour. Clear, dry winter nights give the sharpest city panoramas, and the tower is dramatically floodlit after dark — a favourite backdrop from the surrounding Minato streets.' },
  { id: 'ja5', image: '/images/japan/ja5.jpg', name: 'Mount Fuji Winter View', category: 'Scenic', description: 'Japan\'s iconic mountain is most visible in winter with snow-capped peak against clear blue skies.', bestTime: 'Clear morning', duration: 'Full day trip', photoRating: 5, notes: 'Lake Kawaguchiko offers best winter reflections. Not climbable in winter.', location: 'Yamanashi', mustSee: true, longDescription: 'Mount Fuji, a near-symmetrical volcano and UNESCO site, is most reliably visible in the cold, dry air of winter, its snow-capped cone rising against clear blue skies. The Fuji Five Lakes area in Yamanashi — especially Lake Kawaguchiko — offers the classic reflected view and the Chureito Pagoda vantage. The climbing season is summer only; winter is purely for viewing and photography from the lakes and surrounding towns.' },
  { id: 'ja6', image: '/images/japan/ja6.jpg', name: 'Akihabara Electric Town', category: 'Anime', description: 'Tokyo\'s electronics and anime paradise. Multi-floor arcades, manga shops, maid cafes, and figure stores.', bestTime: 'Afternoon to evening', duration: '3-5 hours', photoRating: 4, notes: 'Visit Super Potato for retro games. Don\'t miss the arcades.', location: 'Akihabara, Tokyo' },
  { id: 'ja7', image: '/images/japan/ja7.jpg', name: 'Kinkaku-ji (Golden Pavilion)', category: 'Must-See', description: 'Zen Buddhist temple covered in gold leaf, reflected in a mirror pond. Stunning in winter with occasional snow.', bestTime: 'Morning', duration: '1-2 hours', photoRating: 5, notes: 'Snow-covered Golden Pavilion is incredibly rare and beautiful.', location: 'Kyoto', mustSee: true, longDescription: 'Kinkaku-ji, the Golden Pavilion, is a Zen temple whose top two floors are entirely covered in gold leaf, mirrored in the still Kyoko-chi ("Mirror Pond") before it. Originally a shogun\'s retirement villa, the current structure is a 1955 reconstruction after arson. A one-way garden path leads past the pavilion and through mossy grounds. A rare dusting of snow on the golden roof is one of Japan\'s most coveted winter photographs.', priceHint: '¥500 entry' },
  { id: 'ja8', image: '/images/japan/ja8.jpg', name: 'TeamLab Borderless', category: 'Experience', description: 'Immersive digital art museum with ever-changing rooms of light, color, and interactive projections.', bestTime: 'Weekday afternoon', duration: '3 hours', photoRating: 5, notes: 'Book tickets in advance. Wear white for best photo effects.', location: 'Azabudai, Tokyo' },
  { id: 'ja9', image: '/images/japan/ja9.jpg', name: 'Meiji Shrine', category: 'Cultural', description: 'Serene Shinto shrine set in a lush forest in central Tokyo. A peaceful retreat from the urban bustle.', bestTime: 'Morning', duration: '1.5 hours', photoRating: 4, notes: 'Write a wish on an ema plaque. New Year visit is special but crowded.', location: 'Harajuku, Tokyo' },
  { id: 'ja10', image: '/images/japan/ja10.jpg', name: 'Arashiyama Bamboo Grove', category: 'Must-See', description: 'A pathway winding through towering bamboo stalks. Winter lighting events add to the atmosphere.', bestTime: 'Early morning', duration: '2 hours', photoRating: 5, notes: 'Arrive before 7 AM for photos without crowds. Hanatouro illumination in December.', location: 'Arashiyama, Kyoto', mustSee: true, longDescription: 'The Arashiyama Bamboo Grove is a short, atmospheric path where towering green bamboo stalks arch overhead and rustle in the wind. It sits in the scenic Arashiyama district of western Kyoto alongside Tenryu-ji temple, the Togetsukyo bridge over the Katsura River, and the Iwatayama monkey park. The grove is free and always open, so an early-morning visit before 8 AM is the only reliable way to photograph it without crowds.', priceHint: 'Free · open access' },
  { id: 'ja11', image: '/images/japan/ja11.jpg', name: 'Tsukiji Outer Market', category: 'Food', description: 'Vibrant food market with fresh sushi, seafood, tamagoyaki, and street food stalls. A food lover\'s paradise.', bestTime: 'Early morning', duration: '2-3 hours', photoRating: 4, notes: 'Come hungry. Try the fresh uni (sea urchin) and tuna sushi.', location: 'Tsukiji, Tokyo' },
  { id: 'ja12', image: '/images/japan/ja12.jpg', name: 'Dotonbori', category: 'Food', description: 'Osaka\'s neon-lit food street famous for takoyaki, okonomiyaki, and giant crab signs. The heart of "Japan\'s Kitchen".', bestTime: 'Evening', duration: '3 hours', photoRating: 5, notes: 'Try Kukuru for takoyaki. Night reflections on the canal are stunning.', location: 'Namba, Osaka' },

  // Hidden Gems
  { id: 'ja13', image: '/images/japan/ja13.jpg', name: 'Yanaka Old Town', category: 'Hidden Gem', description: 'A rare survivor of old Tokyo with narrow lanes, wooden houses, temples, and a nostalgic shopping street (Yanaka Ginza). Escapes the tourist crowds.', bestTime: 'Late morning', duration: '2-3 hours', photoRating: 4, notes: 'Crisp winter light makes the low-rise streets glow. Try a menchi-katsu from Yanaka Ginza.', location: 'Yanaka, Tokyo' },
  { id: 'ja14', image: '/images/japan/ja14.jpg', name: 'Golden Gai', category: 'Hidden Gem', description: 'A warren of six tiny alleys packed with over 200 minuscule themed bars, most seating only a handful of guests. Atmospheric, retro Showa-era Tokyo.', bestTime: 'Night', duration: '2 hours', photoRating: 4, notes: 'Many bars seat 5-6 people and charge a cover. Look for ones with an English-friendly sign.', location: 'Shinjuku, Tokyo' },
  { id: 'ja15', image: '/images/japan/ja15.jpg', name: 'Omoide Yokocho', category: 'Hidden Gem', description: 'Nicknamed "Memory Lane," a smoky lantern-lit alley of cramped yakitori and izakaya stalls under the Shinjuku train tracks. Pure atmospheric Tokyo.', bestTime: 'Evening', duration: '1-2 hours', photoRating: 5, notes: 'Steam rising off grills on a cold winter night is hugely photogenic. Cash is king here.', location: 'Shinjuku, Tokyo' },
  { id: 'ja16', image: '/images/japan/ja16.jpg', name: 'Shimokitazawa', category: 'Hidden Gem', description: 'A bohemian, low-rise neighborhood of vintage clothing stores, indie record shops, tiny theaters, and third-wave coffee. Tokyo\'s relaxed creative side.', bestTime: 'Afternoon', duration: '3 hours', photoRating: 4, notes: 'Best explored on foot with no plan. Great for thrifting winter coats and warm cafe stops.', location: 'Shimokitazawa, Tokyo' },

  // Seasonal Winter Attractions (Dec 19 - Jan 9 trip window)
  { id: 'ja17', image: '/images/japan/ja17.jpg', name: 'Nabana no Sato Winter Illumination', category: 'Winter', description: 'One of Japan\'s largest winter illuminations, with millions of LEDs forming tunnels of light and immersive seasonal light shows in a botanical garden.', bestTime: 'After sunset', duration: '2-3 hours', photoRating: 5, notes: 'Runs through winter into spring — peak season is December–January. The Tunnel of Lights is the signature shot.', location: 'Kuwana, Mie (near Nagoya)', longDescription: 'Nabana no Sato is a botanical garden near Nagoya famous for hosting one of Japan\'s largest and most elaborate winter illuminations. Millions of LEDs form the signature "Tunnel of Lights" and a huge themed light show that changes each season, running from autumn through to spring with December to January as the peak. Admission typically includes a garden voucher; go after sunset for the full effect.' },
  { id: 'ja18', image: '/images/japan/ja18.jpg', name: 'Hakone Onsen Ryokan', category: 'Winter', description: 'Soak in an open-air hot spring (rotenburo) surrounded by winter scenery, often with views toward Mount Fuji. The classic Japanese cold-weather ritual.', bestTime: 'Evening or early morning', duration: 'Overnight', photoRating: 4, notes: 'A steaming outdoor bath in cold December air is the quintessential winter experience. Many ryokan include kaiseki dinner.', location: 'Hakone, Kanagawa' },
  { id: 'ja19', image: '/images/japan/ja19.jpg', name: 'Gala Yuzawa Snow Resort', category: 'Winter', description: 'A ski-and-snow resort reachable directly by bullet train from Tokyo, with slopes, snow play areas, and guaranteed winter snow within a day trip.', bestTime: 'Daytime', duration: 'Full day', photoRating: 4, notes: 'Open from late December. The Gala Yuzawa shinkansen station connects straight to the gondola — ideal for a no-car snow day.', location: 'Yuzawa, Niigata' },
  { id: 'ja20', image: '/images/japan/ja20.jpg', name: 'Shirakawa-go Winter Village', category: 'Winter', description: 'A UNESCO village of steep thatched-roof gassho-zukuri farmhouses, blanketed in deep snow and lit up on select winter evenings — a storybook scene.', bestTime: 'Dusk (light-up evenings)', duration: 'Full day trip', photoRating: 5, notes: 'The winter light-up events fall on limited January dates and require advance reservation. Snow can be waist-deep.', location: 'Shirakawa, Gifu' },
  { id: 'ja21', image: '/images/japan/ja21.jpg', name: 'Roppongi Hills Keyakizaka Illumination', category: 'Winter', description: 'A 400m avenue of zelkova trees draped in blue-and-white "Snow & Blue" LEDs, framed against Tokyo Tower — central Tokyo\'s most photogenic winter lights.', bestTime: 'After dark', duration: '1 hour', photoRating: 5, notes: 'The Tokyo Tower backdrop down Keyakizaka is the iconic December shot. Lights typically run mid-November through December.', location: 'Roppongi, Tokyo' },

  // Anime & Gaming
  { id: 'ja22', image: '/images/japan/ja22.jpg', name: 'Nakano Broadway', category: 'Anime', description: 'A retro multi-floor mall that is a treasure trove for collectors — vintage manga, rare figures, cels, and the original Mandarake flagship. Quieter than Akihabara.', bestTime: 'Afternoon', duration: '2-3 hours', photoRating: 4, notes: 'Less touristy than Akihabara and better for rare/vintage finds. The basement has cult dessert shop Daily Chiko.', location: 'Nakano, Tokyo' },
  { id: 'ja23', image: '/images/japan/ja23.jpg', name: 'Pokémon Center Mega Tokyo', category: 'Anime', description: 'The flagship Pokémon store packed with exclusive plush, apparel, and merchandise, with life-size character displays and limited regional goods.', bestTime: 'Weekday', duration: '1 hour', photoRating: 3, notes: 'Located in Sunshine City, Ikebukuro. Holiday and New Year limited-edition merch appears in December.', location: 'Ikebukuro, Tokyo' },
  { id: 'ja24', image: '/images/japan/ja24.jpg', name: 'Ghibli Museum', category: 'Anime', description: 'A whimsical museum dedicated to Studio Ghibli, with original art, a rooftop robot soldier, a mini theater of exclusive shorts, and dreamlike architecture.', bestTime: 'Morning slot', duration: '2-3 hours', photoRating: 4, notes: 'Tickets are date- and time-stamped and sell out a month ahead — book the instant they release. No photos indoors.', location: 'Mitaka, Tokyo' },
  { id: 'ja25', image: '/images/japan/ja25.jpg', name: 'GiGO Akihabara Arcade', category: 'Anime', description: 'A towering multi-floor game arcade with claw machines, rhythm games, retro cabinets, and gachapon. Pure neon-lit Japanese gaming culture.', bestTime: 'Evening', duration: '1-2 hours', photoRating: 4, notes: 'Floors of UFO-catcher prizes and music games. Bring a stack of 100-yen coins. Warm refuge on a cold night.', location: 'Akihabara, Tokyo' },

  // Shopping Districts
  { id: 'ja26', image: '/images/japan/ja26.jpg', name: 'Ginza Shopping District', category: 'Shopping', description: 'Tokyo\'s most upscale shopping quarter — flagship department stores, luxury boutiques, and the giant Ginza Six and Uniqlo flagships, dressed up for the holidays.', bestTime: 'Afternoon to evening', duration: '3 hours', photoRating: 4, notes: 'Weekend afternoons the main avenue becomes a car-free pedestrian "Hokoten." December window displays are spectacular.', location: 'Ginza, Tokyo' },
  { id: 'ja27', image: '/images/japan/ja27.jpg', name: 'Shinsaibashi & Amerikamura', category: 'Shopping', description: 'Osaka\'s buzzing covered shopping arcade and adjacent youth-fashion district — endless boutiques, drugstores, and streetwear under one long roofed street.', bestTime: 'Afternoon', duration: '2-3 hours', photoRating: 4, notes: 'The covered arcade is a perfect rainy- or cold-day option. Connects straight into Dotonbori for dinner.', location: 'Chuo, Osaka' },

  // — Osaka boys-trip additions (Universal Studios Japan, Den Den Town, Osaka Castle, Kyoto Manga Museum)
  { id: 'ja28', name: 'Universal Studios Japan / Super Nintendo World', category: 'Experience', description: 'Osaka\'s big theme park, anchored by the immersive Super Nintendo World — a Mario Kart ride, Bowser\'s Castle, and interactive power-up bands. A full-day anchor for the Osaka leg.', bestTime: 'Full day, arrive at opening', duration: 'Full day', photoRating: 4, notes: 'Prioritize an Express Pass and check current anime/game collaborations closer to the date.', location: 'Universal Studios Japan, Konohana, Osaka' },
  { id: 'ja29', name: 'Den Den Town / Nipponbashi', category: 'Anime', description: 'Osaka\'s anime and electronics district — a strip of multi-floor shops for figures, retro games, and collectibles. Quieter and less crowded than Tokyo\'s Akihabara.', bestTime: 'Afternoon', duration: '2-3 hours', photoRating: 3, notes: 'Look for One Piece, Naruto and Dragon Ball Z figures and collectibles across the specialty shops.', location: 'Nipponbashi, Osaka' },
  { id: 'ja30', name: 'Osaka Castle', category: 'Must-See', description: 'A grand reconstructed feudal keep ringed by moats and a park of plum and cherry trees, with a panoramic observation deck on top.', bestTime: 'Morning', duration: '2 hours', photoRating: 4, notes: 'The grounds and moat are quiet and crisp in winter; the museum inside covers the castle\'s history.', location: 'Chuo, Osaka' },
  { id: 'ja31', name: 'Kyoto International Manga Museum', category: 'Anime', description: 'A converted 1920s elementary school housing 300,000+ manga volumes across every genre, plus rotating exhibits — a relaxed indoor pick on a recovery day.', bestTime: 'Afternoon', duration: '2-3 hours', photoRating: 3, notes: 'A good flex-day option for the anime-interested — most manga is Japanese-only but the building and exhibits are worth the visit regardless.', location: 'Nakagyo, Kyoto' },
];

export const JAPAN_FOOD: Recommendation[] = [
  { id: 'jf1', image: '/images/japan/jf1.jpg', name: 'Ichiran Ramen', category: 'Ramen', description: 'Famous tonkotsu ramen chain with individual booth seating. Customize your noodle firmness, broth richness, and spice level.', bestTime: 'Anytime', duration: '30min', photoRating: 4, notes: 'Try extra firm noodles (barikata). Order extra noodles (kaedama).', location: 'Multiple locations, Tokyo', longDescription: 'Ichiran is a nationwide tonkotsu (pork-bone) ramen chain known for its solo-dining "flavour concentration booths" — individual partitioned seats where you order via a ticket machine and a paper form, choosing broth richness, garlic, spice and noodle firmness. Bowls arrive through a small hatch. It is a quick, reliably good and famously introvert-friendly ramen experience open long hours in Shibuya, Shinjuku and beyond.' },
  { id: 'jf2', image: '/images/japan/jf2.jpg', name: 'Fuunji Tsukemen', category: 'Ramen', description: 'Shinjuku\'s legendary dipping ramen (tsukemen). Rich, thick fish-based broth with perfectly chewy noodles.', bestTime: 'Lunch', duration: '45min', photoRating: 4, notes: 'Expect a line. Large portion recommended. Finish with soup-wari.', location: 'Shinjuku, Tokyo' },
  { id: 'jf3', image: '/images/japan/jf3.jpg', name: 'Conveyor Belt Sushi', category: 'Sushi', description: 'Fun, affordable sushi on rotating belt. Touch-screen ordering with plates delivered by mini train.', bestTime: 'Lunch', duration: '1 hour', photoRating: 3, notes: 'Sushiro and Kura Sushi are top chains. ¥100-150 per plate.', location: 'Various, Tokyo' },
  { id: 'jf4', image: '/images/japan/jf4.jpg', name: 'Convenience Store Food (Konbini)', category: 'Street Food', description: '7-Eleven, Lawson, FamilyMart serve surprisingly excellent onigiri, sandwiches, fried chicken, and desserts.', bestTime: 'Anytime', duration: '15min', photoRating: 2, notes: 'Lawson\'s karaage is legendary. Try egg sandwiches and melon pan.', location: 'Everywhere' },
  { id: 'jf5', image: '/images/japan/jf5.jpg', name: 'Gyukatsu Motomura', category: 'Restaurant', description: 'Premium deep-fried wagyu beef cutlet cooked to your preference on a hot stone at your table.', bestTime: 'Lunch', duration: '1 hour', photoRating: 4, notes: 'Queue early. Medium rare on the hot stone is perfection.', location: 'Shinjuku, Tokyo' },
  { id: 'jf6', image: '/images/japan/jf6.jpg', name: 'Matcha Desserts at Tsujiri', category: 'Dessert', description: 'Premium matcha from Uji, Kyoto in parfaits, ice cream, and traditional tea. Rich, bitter-sweet green tea perfection.', bestTime: 'Afternoon', duration: '30min', photoRating: 4, notes: 'Kyoto main shop has best selection. Try the matcha parfait.', location: 'Kyoto / Tokyo' },
];

export const JAPAN_CATEGORIES = ['All', 'Must-See', 'Hidden Gem', 'Winter', 'Anime', 'Cultural', 'Scenic', 'Shopping', 'Experience', 'Food', 'Ramen', 'Sushi', 'Street Food', 'Restaurant', 'Dessert'];

// ── The registry itself ───────────────────────────────────────────────────────

/** Mirrors what `lib/nepal-data.ts` / `lib/japan-data.ts` already export — not a redesign. */
export interface LegContent {
  attractions: Recommendation[];
  food: Recommendation[];
  categories: string[];
}

export interface TripContent {
  itinerary: DayPlan[];
  legs: Record<string, LegContent>;
}

/** === `TripConfig.contentRef` for the default pack (core/trips/packs/nepal-japan-2026.ts). */
export const DEFAULT_CONTENT_REF = 'nepal-japan-2026';

const NEPAL_JAPAN_2026_CONTENT: TripContent = {
  itinerary: TRIP_ITINERARY,
  legs: {
    nepal: { attractions: NEPAL_ATTRACTIONS, food: NEPAL_FOOD, categories: NEPAL_CATEGORIES },
    japan: { attractions: JAPAN_ATTRACTIONS, food: JAPAN_FOOD, categories: JAPAN_CATEGORIES },
  },
};

/** Static registry — one pack today; a second pack's content is a future concern, not now. */
export const CONTENT_PACKS: Record<string, TripContent> = {
  [DEFAULT_CONTENT_REF]: NEPAL_JAPAN_2026_CONTENT,
};

/** TOTAL — an unknown `contentRef` falls back to the default pack's content, never throws. */
export function getContent(contentRef: string): TripContent {
  return CONTENT_PACKS[contentRef] ?? NEPAL_JAPAN_2026_CONTENT;
}

/** TOTAL — an unknown `contentKey` within a resolved TripContent falls back to empty content. */
export function getLegContent(content: TripContent, contentKey: string): LegContent {
  return content.legs[contentKey] ?? { attractions: [], food: [], categories: [] };
}
