import { Recommendation } from './nepal-data';

export const JAPAN_ATTRACTIONS: Recommendation[] = [
  { id: 'ja1', image: '/images/japan/ja1.jpg', name: 'Senso-ji Temple', category: 'Must-See', description: 'Tokyo\'s oldest and most significant Buddhist temple. The Thunder Gate (Kaminarimon) and Nakamise shopping street are iconic.', bestTime: 'Early morning or night', duration: '2-3 hours', photoRating: 5, notes: 'Visit at dawn for empty shots. Night illumination is magical.', location: 'Asakusa, Tokyo' },
  { id: 'ja2', image: '/images/japan/ja2.jpg', name: 'Fushimi Inari Shrine', category: 'Must-See', description: 'Thousands of vermillion torii gates winding up a mountainside. One of the most photographed sites in Japan.', bestTime: 'Dawn or dusk', duration: '2-4 hours', photoRating: 5, notes: 'Go early to avoid crowds. Full hike to summit takes 2-3 hours.', location: 'Kyoto' },
  { id: 'ja3', image: '/images/japan/ja3.jpg', name: 'Shibuya Crossing', category: 'Must-See', description: 'The world\'s busiest pedestrian crossing. Up to 3,000 people cross simultaneously. An icon of Tokyo\'s urban energy.', bestTime: 'Evening rush hour', duration: '1 hour', photoRating: 5, notes: 'Best viewed from Shibuya Sky observation deck or Starbucks.', location: 'Shibuya, Tokyo' },
  { id: 'ja4', image: '/images/japan/ja4.jpg', name: 'Tokyo Tower', category: 'Must-See', description: 'A 333m communications tower with observation decks looking out over the city, especially good at night.', bestTime: 'Sunset to night', duration: '1.5 hours', photoRating: 5, notes: 'Winter nights offer the clearest views. Top deck worth the extra fee.', location: 'Minato, Tokyo' },
  { id: 'ja5', image: '/images/japan/ja5.jpg', name: 'Mount Fuji Winter View', category: 'Scenic', description: 'Japan\'s iconic mountain is most visible in winter with snow-capped peak against clear blue skies.', bestTime: 'Clear morning', duration: 'Full day trip', photoRating: 5, notes: 'Lake Kawaguchiko offers best winter reflections. Not climbable in winter.', location: 'Yamanashi' },
  { id: 'ja6', image: '/images/japan/ja6.jpg', name: 'Akihabara Electric Town', category: 'Anime', description: 'Tokyo\'s electronics and anime paradise. Multi-floor arcades, manga shops, maid cafes, and figure stores.', bestTime: 'Afternoon to evening', duration: '3-5 hours', photoRating: 4, notes: 'Visit Super Potato for retro games. Don\'t miss the arcades.', location: 'Akihabara, Tokyo' },
  { id: 'ja7', image: '/images/japan/ja7.jpg', name: 'Kinkaku-ji (Golden Pavilion)', category: 'Must-See', description: 'Zen Buddhist temple covered in gold leaf, reflected in a mirror pond. Stunning in winter with occasional snow.', bestTime: 'Morning', duration: '1-2 hours', photoRating: 5, notes: 'Snow-covered Golden Pavilion is incredibly rare and beautiful.', location: 'Kyoto' },
  { id: 'ja8', name: 'TeamLab Borderless', category: 'Experience', description: 'Immersive digital art museum with ever-changing rooms of light, color, and interactive projections.', bestTime: 'Weekday afternoon', duration: '3 hours', photoRating: 5, notes: 'Book tickets in advance. Wear white for best photo effects.', location: 'Azabudai, Tokyo' },
  { id: 'ja9', image: '/images/japan/ja9.jpg', name: 'Meiji Shrine', category: 'Cultural', description: 'Serene Shinto shrine set in a lush forest in central Tokyo. A peaceful retreat from the urban bustle.', bestTime: 'Morning', duration: '1.5 hours', photoRating: 4, notes: 'Write a wish on an ema plaque. New Year visit is special but crowded.', location: 'Harajuku, Tokyo' },
  { id: 'ja10', image: '/images/japan/ja10.jpg', name: 'Arashiyama Bamboo Grove', category: 'Must-See', description: 'A pathway winding through towering bamboo stalks. Winter lighting events add to the atmosphere.', bestTime: 'Early morning', duration: '2 hours', photoRating: 5, notes: 'Arrive before 7 AM for photos without crowds. Hanatouro illumination in December.', location: 'Arashiyama, Kyoto' },
  { id: 'ja11', image: '/images/japan/ja11.jpg', name: 'Tsukiji Outer Market', category: 'Food', description: 'Vibrant food market with fresh sushi, seafood, tamagoyaki, and street food stalls. A food lover\'s paradise.', bestTime: 'Early morning', duration: '2-3 hours', photoRating: 4, notes: 'Come hungry. Try the fresh uni (sea urchin) and tuna sushi.', location: 'Tsukiji, Tokyo' },
  { id: 'ja12', image: '/images/japan/ja12.jpg', name: 'Dotonbori', category: 'Food', description: 'Osaka\'s neon-lit food street famous for takoyaki, okonomiyaki, and giant crab signs. The heart of "Japan\'s Kitchen".', bestTime: 'Evening', duration: '3 hours', photoRating: 5, notes: 'Try Kukuru for takoyaki. Night reflections on the canal are stunning.', location: 'Namba, Osaka' },

  // Hidden Gems
  { id: 'ja13', image: '/images/japan/ja13.jpg', name: 'Yanaka Old Town', category: 'Hidden Gem', description: 'A rare survivor of old Tokyo with narrow lanes, wooden houses, temples, and a nostalgic shopping street (Yanaka Ginza). Escapes the tourist crowds.', bestTime: 'Late morning', duration: '2-3 hours', photoRating: 4, notes: 'Crisp winter light makes the low-rise streets glow. Try a menchi-katsu from Yanaka Ginza.', location: 'Yanaka, Tokyo' },
  { id: 'ja14', image: '/images/japan/ja14.jpg', name: 'Golden Gai', category: 'Hidden Gem', description: 'A warren of six tiny alleys packed with over 200 minuscule themed bars, most seating only a handful of guests. Atmospheric, retro Showa-era Tokyo.', bestTime: 'Night', duration: '2 hours', photoRating: 4, notes: 'Many bars seat 5-6 people and charge a cover. Look for ones with an English-friendly sign.', location: 'Shinjuku, Tokyo' },
  { id: 'ja15', name: 'Omoide Yokocho', category: 'Hidden Gem', description: 'Nicknamed "Memory Lane," a smoky lantern-lit alley of cramped yakitori and izakaya stalls under the Shinjuku train tracks. Pure atmospheric Tokyo.', bestTime: 'Evening', duration: '1-2 hours', photoRating: 5, notes: 'Steam rising off grills on a cold winter night is hugely photogenic. Cash is king here.', location: 'Shinjuku, Tokyo' },
  { id: 'ja16', image: '/images/japan/ja16.jpg', name: 'Shimokitazawa', category: 'Hidden Gem', description: 'A bohemian, low-rise neighborhood of vintage clothing stores, indie record shops, tiny theaters, and third-wave coffee. Tokyo\'s relaxed creative side.', bestTime: 'Afternoon', duration: '3 hours', photoRating: 4, notes: 'Best explored on foot with no plan. Great for thrifting winter coats and warm cafe stops.', location: 'Shimokitazawa, Tokyo' },

  // Seasonal Winter Attractions (Dec 19 - Jan 9 trip window)
  { id: 'ja17', image: '/images/japan/ja17.jpg', name: 'Nabana no Sato Winter Illumination', category: 'Winter', description: 'One of Japan\'s largest winter illuminations, with millions of LEDs forming tunnels of light and immersive seasonal light shows in a botanical garden.', bestTime: 'After sunset', duration: '2-3 hours', photoRating: 5, notes: 'Runs through winter into spring — peak season is December–January. The Tunnel of Lights is the signature shot.', location: 'Kuwana, Mie (near Nagoya)' },
  { id: 'ja18', image: '/images/japan/ja18.jpg', name: 'Hakone Onsen Ryokan', category: 'Winter', description: 'Soak in an open-air hot spring (rotenburo) surrounded by winter scenery, often with views toward Mount Fuji. The classic Japanese cold-weather ritual.', bestTime: 'Evening or early morning', duration: 'Overnight', photoRating: 4, notes: 'A steaming outdoor bath in cold December air is the quintessential winter experience. Many ryokan include kaiseki dinner.', location: 'Hakone, Kanagawa' },
  { id: 'ja19', image: '/images/japan/ja19.jpg', name: 'Gala Yuzawa Snow Resort', category: 'Winter', description: 'A ski-and-snow resort reachable directly by bullet train from Tokyo, with slopes, snow play areas, and guaranteed winter snow within a day trip.', bestTime: 'Daytime', duration: 'Full day', photoRating: 4, notes: 'Open from late December. The Gala Yuzawa shinkansen station connects straight to the gondola — ideal for a no-car snow day.', location: 'Yuzawa, Niigata' },
  { id: 'ja20', image: '/images/japan/ja20.jpg', name: 'Shirakawa-go Winter Village', category: 'Winter', description: 'A UNESCO village of steep thatched-roof gassho-zukuri farmhouses, blanketed in deep snow and lit up on select winter evenings — a storybook scene.', bestTime: 'Dusk (light-up evenings)', duration: 'Full day trip', photoRating: 5, notes: 'The winter light-up events fall on limited January dates and require advance reservation. Snow can be waist-deep.', location: 'Shirakawa, Gifu' },
  { id: 'ja21', image: '/images/japan/ja21.jpg', name: 'Roppongi Hills Keyakizaka Illumination', category: 'Winter', description: 'A 400m avenue of zelkova trees draped in blue-and-white "Snow & Blue" LEDs, framed against Tokyo Tower — central Tokyo\'s most photogenic winter lights.', bestTime: 'After dark', duration: '1 hour', photoRating: 5, notes: 'The Tokyo Tower backdrop down Keyakizaka is the iconic December shot. Lights typically run mid-November through December.', location: 'Roppongi, Tokyo' },

  // Anime & Gaming
  { id: 'ja22', image: '/images/japan/ja22.jpg', name: 'Nakano Broadway', category: 'Anime', description: 'A retro multi-floor mall that is a treasure trove for collectors — vintage manga, rare figures, cels, and the original Mandarake flagship. Quieter than Akihabara.', bestTime: 'Afternoon', duration: '2-3 hours', photoRating: 4, notes: 'Less touristy than Akihabara and better for rare/vintage finds. The basement has cult dessert shop Daily Chiko.', location: 'Nakano, Tokyo' },
  { id: 'ja23', image: '/images/japan/ja23.jpg', name: 'Pokémon Center Mega Tokyo', category: 'Anime', description: 'The flagship Pokémon store packed with exclusive plush, apparel, and merchandise, with life-size character displays and limited regional goods.', bestTime: 'Weekday', duration: '1 hour', photoRating: 3, notes: 'Located in Sunshine City, Ikebukuro. Holiday and New Year limited-edition merch appears in December.', location: 'Ikebukuro, Tokyo' },
  { id: 'ja24', image: '/images/japan/ja24.jpg', name: 'Ghibli Museum', category: 'Anime', description: 'A whimsical museum dedicated to Studio Ghibli, with original art, a rooftop robot soldier, a mini theater of exclusive shorts, and dreamlike architecture.', bestTime: 'Morning slot', duration: '2-3 hours', photoRating: 4, notes: 'Tickets are date- and time-stamped and sell out a month ahead — book the instant they release. No photos indoors.', location: 'Mitaka, Tokyo' },
  { id: 'ja25', image: '/images/japan/ja25.jpg', name: 'GiGO Akihabara Arcade', category: 'Anime', description: 'A towering multi-floor game arcade with claw machines, rhythm games, retro cabinets, and gachapon. Pure neon-lit Japanese gaming culture.', bestTime: 'Evening', duration: '1-2 hours', photoRating: 4, notes: 'Floors of UFO-catcher prizes and music games. Bring a stack of 100-yen coins. Warm refuge on a cold night.', location: 'Akihabara, Tokyo' },

  // Shopping Districts
  { id: 'ja26', image: '/images/japan/ja26.jpg', name: 'Ginza Shopping District', category: 'Shopping', description: 'Tokyo\'s most upscale shopping quarter — flagship department stores, luxury boutiques, and the giant Ginza Six and Uniqlo flagships, dressed up for the holidays.', bestTime: 'Afternoon to evening', duration: '3 hours', photoRating: 4, notes: 'Weekend afternoons the main avenue becomes a car-free pedestrian "Hokoten." December window displays are spectacular.', location: 'Ginza, Tokyo' },
  { id: 'ja27', image: '/images/japan/ja27.jpg', name: 'Shinsaibashi & Amerikamura', category: 'Shopping', description: 'Osaka\'s buzzing covered shopping arcade and adjacent youth-fashion district — endless boutiques, drugstores, and streetwear under one long roofed street.', bestTime: 'Afternoon', duration: '2-3 hours', photoRating: 4, notes: 'The covered arcade is a perfect rainy- or cold-day option. Connects straight into Dotonbori for dinner.', location: 'Chuo, Osaka' },
];

export const JAPAN_FOOD: Recommendation[] = [
  { id: 'jf1', image: '/images/japan/jf1.jpg', name: 'Ichiran Ramen', category: 'Ramen', description: 'Famous tonkotsu ramen chain with individual booth seating. Customize your noodle firmness, broth richness, and spice level.', bestTime: 'Anytime', duration: '30min', photoRating: 4, notes: 'Try extra firm noodles (barikata). Order extra noodles (kaedama).', location: 'Multiple locations, Tokyo' },
  { id: 'jf2', image: '/images/japan/jf2.jpg', name: 'Fuunji Tsukemen', category: 'Ramen', description: 'Shinjuku\'s legendary dipping ramen (tsukemen). Rich, thick fish-based broth with perfectly chewy noodles.', bestTime: 'Lunch', duration: '45min', photoRating: 4, notes: 'Expect a line. Large portion recommended. Finish with soup-wari.', location: 'Shinjuku, Tokyo' },
  { id: 'jf3', image: '/images/japan/jf3.jpg', name: 'Conveyor Belt Sushi', category: 'Sushi', description: 'Fun, affordable sushi on rotating belt. Touch-screen ordering with plates delivered by mini train.', bestTime: 'Lunch', duration: '1 hour', photoRating: 3, notes: 'Sushiro and Kura Sushi are top chains. ¥100-150 per plate.', location: 'Various, Tokyo' },
  { id: 'jf4', image: '/images/japan/jf4.jpg', name: 'Convenience Store Food (Konbini)', category: 'Street Food', description: '7-Eleven, Lawson, FamilyMart serve surprisingly excellent onigiri, sandwiches, fried chicken, and desserts.', bestTime: 'Anytime', duration: '15min', photoRating: 2, notes: 'Lawson\'s karaage is legendary. Try egg sandwiches and melon pan.', location: 'Everywhere' },
  { id: 'jf5', image: '/images/japan/jf5.jpg', name: 'Gyukatsu Motomura', category: 'Restaurant', description: 'Premium deep-fried wagyu beef cutlet cooked to your preference on a hot stone at your table.', bestTime: 'Lunch', duration: '1 hour', photoRating: 4, notes: 'Queue early. Medium rare on the hot stone is perfection.', location: 'Shinjuku, Tokyo' },
  { id: 'jf6', image: '/images/japan/jf6.jpg', name: 'Matcha Desserts at Tsujiri', category: 'Dessert', description: 'Premium matcha from Uji, Kyoto in parfaits, ice cream, and traditional tea. Rich, bitter-sweet green tea perfection.', bestTime: 'Afternoon', duration: '30min', photoRating: 4, notes: 'Kyoto main shop has best selection. Try the matcha parfait.', location: 'Kyoto / Tokyo' },
];

export const JAPAN_CATEGORIES = ['All', 'Must-See', 'Hidden Gem', 'Winter', 'Anime', 'Cultural', 'Scenic', 'Shopping', 'Experience', 'Food', 'Ramen', 'Sushi', 'Street Food', 'Restaurant', 'Dessert'];
