export interface Recommendation {
  id: string;
  name: string;
  category: string;
  description: string;
  bestTime: string;
  duration: string;
  photoRating: number;
  notes: string;
  location?: string;
  image?: string;
  // --- optional enrichment fields (additive; nothing existing breaks) ---
  /** Curated genuine highlight — drives the "Must-see" badge (~5-8 per country). */
  mustSee?: boolean;
  /** Longer, accurate description shown in the detail sheet. Real facts only. */
  longDescription?: string;
  /** Practical fee/price hint (e.g. "NPR 1000 foreigner entry"). Omit if unknown. */
  priceHint?: string;
}

export const NEPAL_ATTRACTIONS: Recommendation[] = [
  // --- Temples & Cultural Sites ---
  { id: 'na1', image: '/images/nepal/na1.jpg', name: 'Boudhanath Stupa', category: 'Temple', description: 'One of the largest spherical stupas in Nepal, a UNESCO World Heritage Site. The mandala-design dome is surrounded by prayer wheels and monasteries.', bestTime: 'Early morning or sunset', duration: '2-3 hours', photoRating: 5, notes: 'Walk clockwise around the stupa. Best light at golden hour.', location: 'Boudha, Kathmandu', mustSee: true, longDescription: 'Boudhanath is one of the largest stupas in the world and the centre of Tibetan Buddhism in Nepal. The colossal white dome, topped by a gilded tower painted with the all-seeing eyes of the Buddha, was rebuilt after the 2015 earthquake. It sits at the heart of a bustling neighbourhood of monasteries (gompas), thangka workshops and rooftop cafes, and comes alive at dusk when pilgrims circle it clockwise spinning prayer wheels and lighting butter lamps.' },
  { id: 'na2', image: '/images/nepal/na2.jpg', name: 'Swayambhunath (Monkey Temple)', category: 'Temple', description: 'Ancient religious complex atop a hill with panoramic views of Kathmandu Valley. Watch playful monkeys and explore Buddhist and Hindu shrines.', bestTime: 'Sunrise', duration: '2 hours', photoRating: 5, notes: '365 steps to the top. Bring wide-angle lens for cityscape.', location: 'Swayambhu Hill', mustSee: true, longDescription: 'Perched on a hilltop west of the city, Swayambhunath is one of the oldest religious sites in Nepal, its central stupa crowned by the painted eyes of the Buddha gazing in four directions. A steep flight of 365 stone steps lined with prayer flags and resident rhesus macaques (hence "Monkey Temple") climbs to a complex where Buddhist and Hindu shrines mingle. The summit offers one of the best panoramas of the Kathmandu Valley, especially at first light.' },
  { id: 'na3', image: '/images/nepal/na3.jpg', name: 'Pashupatinath Temple', category: 'Temple', description: 'Sacred Hindu temple on the banks of the Bagmati River. Witness cremation ceremonies and the evening aarti ritual.', bestTime: 'Morning or evening aarti', duration: '2-3 hours', photoRating: 4, notes: 'Non-Hindus cannot enter main temple. Cremation photography requires sensitivity.', location: 'Pashupatinath', mustSee: true, longDescription: 'Pashupatinath is Nepal\'s most sacred Hindu temple complex, a sprawling UNESCO-listed site on the banks of the holy Bagmati River dedicated to Lord Shiva. Non-Hindus cannot enter the golden-roofed main temple but can watch openly from the opposite bank, where riverside ghats host public cremations and, each evening, a mesmerising Bagmati aarti of fire, chanting and bells. Sadhus (holy men) in ochre robes and ash gather in the surrounding courtyards.' },
  { id: 'na11', image: '/images/nepal/na11.jpg', name: 'Budhanilkantha Temple', category: 'Temple', description: 'Home to Nepal\'s largest stone statue of the reclining Vishnu, carved from a single block of black basalt and floating in a recessed water tank.', bestTime: 'Early morning', duration: '1-2 hours', photoRating: 4, notes: 'The 5-metre sleeping Vishnu dates to the 7th century. Quiet and uncrowded at dawn.', location: 'Budhanilkantha, north Kathmandu' },
  { id: 'na12', image: '/images/nepal/na12.jpg', name: 'Changu Narayan Temple', category: 'Temple', description: 'The oldest Hindu temple in the Kathmandu Valley and a UNESCO site, famed for exquisite 5th-century stone, wood and metal craftsmanship.', bestTime: 'Morning', duration: '2 hours', photoRating: 5, notes: 'Pair with a short hike down to Bhaktapur or Nagarkot. Newari woodcarving at its finest.', location: 'Changunarayan hill' },

  // --- Must-Visit (Durbar Squares) ---
  { id: 'na4', image: '/images/nepal/na4.jpg', name: 'Kathmandu Durbar Square', category: 'Must-Visit', description: 'Historic royal palace square with temples, courtyards, and the living goddess Kumari. A UNESCO site showcasing Newari architecture.', bestTime: 'Morning', duration: '3 hours', photoRating: 5, notes: 'Visit Kumari Ghar to see the living goddess. Entry fee for foreigners.', location: 'Basantapur', mustSee: true, longDescription: 'The old royal square at the heart of Kathmandu (also called Hanuman Dhoka) is a UNESCO World Heritage Site packed with pagoda temples, courtyards and the former royal palace, all in intricate Newari brick-and-timber style. It is home to the Kumari Ghar, residence of the living goddess who occasionally appears at a carved window. Some structures were lost in the 2015 earthquake and restoration continues, but the square remains a living centre of ritual and daily life.' },
  { id: 'na5', image: '/images/nepal/na5.jpg', name: 'Patan Durbar Square', category: 'Must-Visit', description: 'A dense collection of Newari architecture. Krishna Temple, the Golden Temple, and the Patan Museum ring the square.', bestTime: 'Morning to afternoon', duration: '3-4 hours', photoRating: 5, notes: 'The Patan Museum is well worth the time. Explore surrounding alleys for hidden courtyards.', location: 'Lalitpur', mustSee: true, longDescription: 'Across the Bagmati in the city of Lalitpur, Patan Durbar Square is often considered the finest concentration of Newari architecture in the valley. Highlights include the stone Krishna Mandir carved from a single shikhara-style block, the gilded Golden Temple (Hiranya Varna Mahavihar), and the acclaimed Patan Museum housed in a restored palace wing. The surrounding lanes of Patan hide countless Buddhist courtyards (bahals) and metalworking workshops.' },
  { id: 'na6', image: '/images/nepal/na6.jpg', name: 'Bhaktapur Durbar Square', category: 'Must-Visit', description: 'Best preserved medieval city in the Kathmandu Valley. 55-Window Palace, Nyatapola Temple, and traditional pottery squares.', bestTime: 'Full day visit', duration: '5-6 hours', photoRating: 5, notes: 'Try the famous Juju Dhau (King Curd). Least touristy of the three squares.', mustSee: true, longDescription: 'Bhaktapur is the best-preserved medieval town in the Kathmandu Valley, a UNESCO site where car-free brick lanes open onto three linked squares. The Durbar Square holds the 55-Window Palace and the Golden Gate; nearby Taumadhi Square is dominated by the five-tiered Nyatapola, Nepal\'s tallest pagoda, while Pottery Square is still lined with potters spinning clay in the open air. It is famous for its creamy Juju Dhau ("king curd").' },

  // --- Hidden Gems ---
  { id: 'na7', image: '/images/nepal/na7.jpg', name: 'Garden of Dreams', category: 'Hidden Gem', description: 'A neo-classical garden oasis in the heart of Kathmandu. Fountains, pergolas, and peaceful pavilions away from city chaos.', bestTime: 'Afternoon', duration: '1-2 hours', photoRating: 4, notes: 'Perfect escape from bustling Thamel. Small entry fee.', location: 'Keshar Mahal, Kathmandu', longDescription: 'A restored 1920s neo-classical garden built by a Rana general, the Garden of Dreams is a walled Edwardian oasis of pavilions, pergolas, fountains and a lily pond right beside Thamel. Beautifully renovated with Austrian support, it is a favourite spot to escape the noise of the city with a coffee at the Kaiser Cafe. It sits directly next to the Tulsi Kathmandu Hotel area.' },
  { id: 'na8', image: '/images/nepal/na8.jpg', name: 'Asan Bazaar', category: 'Hidden Gem', description: 'The oldest and most vibrant market in Kathmandu. Spices, vegetables, fabrics, and hidden temples in narrow alleyways.', bestTime: 'Morning', duration: '2 hours', photoRating: 5, notes: 'Best street photography spot in KTM. Follow the ancient trade route.', location: 'Asan, Kathmandu', longDescription: 'Asan is the oldest and busiest bazaar in Kathmandu, a six-way junction on the historic trade route to Tibet. Its dense lanes overflow with vendors selling spices, grains, textiles, brass and fresh produce, and the small Annapurna and Ganesh temples at its centre are still active. Go in the morning for the most energetic scenes — it is widely regarded as the best street-photography spot in the city.' },
  { id: 'na13', image: '/images/nepal/na13.jpg', name: 'Pharping & Asura Cave', category: 'Hidden Gem', description: 'A serene cluster of Buddhist monasteries and the sacred Asura Cave where Guru Rinpoche meditated, set in pine-forested hills south of the valley.', bestTime: 'Morning', duration: 'Half day', photoRating: 4, notes: 'Combine with the Dakshinkali temple nearby. Peaceful and rarely crowded.', location: 'Pharping' },

  // --- Nature ---
  { id: 'na9', image: '/images/nepal/na9.jpg', name: 'Shivapuri National Park', category: 'Nature', description: 'Lush forested national park on the valley\'s northern rim with hiking trails, waterfalls and the Bagmati river source. Rich birdlife and mountain air.', bestTime: 'Morning', duration: 'Half to full day', photoRating: 4, notes: 'Trailhead near Budhanilkantha. Good for a half-day forest hike.', location: 'Shivapuri-Nagarjun' },
  { id: 'na10', image: '/images/nepal/na10.jpg', name: 'Taudaha Lake', category: 'Nature', description: 'A tranquil natural lake on the valley\'s southern edge, a winter stopover for migratory birds and a calm spot for a quiet walk away from the city.', bestTime: 'Late afternoon', duration: '1-2 hours', photoRating: 3, notes: 'Best birdwatching in December. Tea stalls along the shore.', location: 'Chobhar' },

  // --- Photography Locations ---
  { id: 'na14', image: '/images/nepal/na14.jpg', name: 'Chobhar Gorge', category: 'Photography', description: 'A dramatic river gorge where the Bagmati cuts through the valley rim, with the Jal Binayak temple and a vintage suspension bridge framing the water.', bestTime: 'Late afternoon', duration: '1-2 hours', photoRating: 4, notes: 'Wide-angle for the gorge, telephoto for temple detail. Soft side light after 3 PM.', location: 'Chobhar' },
  { id: 'na15', image: '/images/nepal/na15.jpg', name: 'Kopan Monastery Viewpoint', category: 'Photography', description: 'A hilltop Buddhist monastery overlooking Boudhanath and the valley, with prayer flags, golden roofs and sweeping skyline compositions.', bestTime: 'Sunset', duration: '1-2 hours', photoRating: 5, notes: 'Frame Boudhanath stupa against the city below at dusk. Respect monastery quiet hours.', location: 'Kopan hill, Boudha' },
  { id: 'na16', image: '/images/nepal/na16.jpg', name: 'Sarangkot-style Valley Rim at Phulchowki', category: 'Photography', description: 'The valley\'s highest rim peak, blanketed in rhododendron forest, offering layered ridge-line and Himalayan panorama shots on clear winter mornings.', bestTime: 'Pre-dawn to early morning', duration: 'Half day', photoRating: 5, notes: 'Clearest December skies reveal distant peaks. Bring a telephoto for compressed ridges.', location: 'Phulchowki, Godavari' },

  // --- Day Trips ---
  { id: 'na17', image: '/images/nepal/na17.jpg', name: 'Nagarkot Sunrise', category: 'Day Trip', description: 'Famous hilltop viewpoint offering panoramic sunrise views over the Himalayan range including Everest, Langtang and Ganesh Himal.', bestTime: 'Pre-dawn to sunrise', duration: 'Half day', photoRating: 5, notes: 'Leave Kathmandu by 4:30 AM. Bring tripod and telephoto lens.', location: 'Nagarkot', mustSee: true, longDescription: 'Nagarkot is a ridge-top village about 30 km east of Kathmandu, famed for its sweeping Himalayan horizon. On clear winter mornings the sunrise reveals a long arc of peaks — including the Langtang, Ganesh Himal and Rolwaling ranges, and on the clearest days a distant glimpse of Everest. December offers some of the year\'s best visibility. Stay overnight or leave the city very early to catch first light from a viewpoint tower.' },
  { id: 'na18', image: '/images/nepal/na18.jpg', name: 'Chandragiri Hills Cable Car', category: 'Day Trip', description: 'Cable car ride to a hilltop with stunning views of the Himalayas and Kathmandu Valley. Clear winter days offer Everest views.', bestTime: 'Clear morning', duration: '3-4 hours', photoRating: 5, notes: 'December offers clearest mountain views. Bring layers for cold at the top.', location: 'Chandragiri' },
  { id: 'na19', image: '/images/nepal/na19.jpg', name: 'Dhulikhel', category: 'Day Trip', description: 'A historic Newari town on the valley\'s eastern edge with cobbled streets, traditional architecture and a renowned wraparound Himalayan panorama.', bestTime: 'Sunrise or sunset', duration: 'Full day', photoRating: 5, notes: 'About 30 km from Kathmandu. Walk the ridge to the Kali shrine viewpoint.', location: 'Dhulikhel, Kavre' },
  { id: 'na20', image: '/images/nepal/na20.jpg', name: 'Namo Buddha', category: 'Day Trip', description: 'One of Tibetan Buddhism\'s holiest sites, home to the Thrangu Tashi Yangtse Monastery set among terraced hills and forest stupas.', bestTime: 'Morning', duration: 'Full day', photoRating: 4, notes: 'Pair with Dhulikhel and Panauti for a scenic loop. Vegetarian meals at the monastery.', location: 'Namobuddha, Kavre' },
];

export const NEPAL_FOOD: Recommendation[] = [
  { id: 'nf1', image: '/images/nepal/nf1.jpeg', name: 'Bhojan Griha', category: 'Food', description: 'Traditional Nepali feast in a 150-year-old heritage building with cultural performances. Multi-course dal bhat dinner.', bestTime: 'Dinner', duration: '2 hours', photoRating: 4, notes: 'Reservation recommended. Cultural dance show included.', location: 'Dillibazar, Kathmandu', longDescription: 'Set in a lovingly restored 19th-century Rana-era mansion in Dillibazar, Bhojan Griha serves a multi-course traditional Nepali feast (a fixed set menu of dal bhat, curries, pickles and sweets) accompanied by live folk music and dance performances. It is a popular, atmospheric introduction to Newari and hill-Nepali cuisine — reservations are recommended, especially in the evening.' },
  { id: 'nf2', image: '/images/nepal/nf2.jpg', name: 'Yangling Restaurant', category: 'Food', description: 'Legendary momo spot in Thamel. Steamed, fried, and jhol momos with authentic Tibetan-Nepali flavors.', bestTime: 'Lunch', duration: '1 hour', photoRating: 3, notes: 'Try the jhol (soup) momos. Simple atmosphere, incredible food.' },
  { id: 'nf3', image: '/images/nepal/nf3.jpg', name: 'OR2K Restaurant', category: 'Café', description: 'Mediterranean-Nepali fusion with stunning rooftop views. Cushion seating, hookah-friendly, great hummus and falafel.', bestTime: 'Breakfast or sunset', duration: '1.5 hours', photoRating: 4, notes: 'Rooftop sunset views are magical. Vegetarian-friendly.' },
  { id: 'nf4', image: '/images/nepal/nf4.jpg', name: 'Cafe Swotha', category: 'Food', description: 'Newari cuisine served in a beautifully restored heritage courtyard in Patan. Authentic local flavors in elegant setting.', bestTime: 'Lunch', duration: '1.5 hours', photoRating: 4, notes: 'Try the Newari set meal. Beautiful courtyard architecture.' },
  { id: 'nf5', image: '/images/nepal/nf5.jpg', name: 'Roadhouse Cafe', category: 'Café', description: 'Best wood-fired pizza in Kathmandu with craft beer selection. Modern atmosphere, popular with expats.', bestTime: 'Dinner', duration: '1.5 hours', photoRating: 3, notes: 'Multiple locations. Thamel branch has best atmosphere.' },
  { id: 'nf6', image: '/images/nepal/nf6.jpeg', name: 'Thakali Kitchen', category: 'Food', description: 'Authentic Thakali dal bhat - the quintessential Nepali meal. Unlimited refills on rice, dal, vegetables.', bestTime: 'Lunch', duration: '1 hour', photoRating: 3, notes: 'Eat with right hand for authentic experience. Dal bhat power!' },
  { id: 'nf7', image: '/images/nepal/nf7.jpg', name: 'Himalayan Java', category: 'Café', description: 'Nepal\'s premier coffee chain using locally grown beans from the hills. Multiple scenic locations across Kathmandu.', bestTime: 'Morning', duration: '1 hour', photoRating: 3, notes: 'Try Nepali-grown coffee. Garden-view branch near Thamel is best.' },
];

export const NEPAL_CATEGORIES = ['All', 'Must-Visit', 'Hidden Gem', 'Temple', 'Food', 'Café', 'Nature', 'Photography', 'Day Trip'];
