export interface NightlifeVenue {
  id: string;
  name: string;
  country: 'Nepal' | 'Japan';
  location: string;
  vibe: string;
  musicType: string;
  priceRange: string;
  bestDays: string;
  description: string;
  // --- optional enrichment ---
  /** Curated genuine highlight — drives the "Must-see" badge. */
  mustSee?: boolean;
  /** Longer, accurate description shown in the detail sheet. Real facts only. */
  longDescription?: string;
}

export const NIGHTLIFE_VENUES: NightlifeVenue[] = [
  { id: 'nl1', name: 'Purple Haze Rock Bar', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Rock & live music', musicType: 'Rock, Blues, Indie', priceRange: '$$', bestDays: 'Fri-Sat', description: 'Kathmandu\'s legendary live music venue. Local and international bands perform nightly in an intimate setting.', mustSee: true, longDescription: 'Purple Haze is one of Kathmandu\'s best-known live-music bars, a large multi-level venue in the heart of Thamel that hosts local and touring rock, blues and indie bands most nights. Named after the Hendrix track, it draws a mixed crowd of travellers and locals and gets loud and lively at weekends — arrive early for a spot near the stage.' },
  { id: 'nl2', name: 'Sam\'s Bar', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Backpacker social hub', musicType: 'Mixed / DJ', priceRange: '$', bestDays: 'Every night', description: 'The most famous bar in Thamel. Pool tables, cheap drinks, and a melting pot of travelers from around the world.' },
  { id: 'nl3', name: 'LOD (Lord of the Drinks)', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Upscale lounge', musicType: 'House, Electronic', priceRange: '$$$', bestDays: 'Thu-Sat', description: 'Multi-level upscale lounge with rooftop terrace. Premium cocktails and modern ambiance.' },
  { id: 'nl4', name: 'Club Fahrenheit', country: 'Nepal', location: 'Durbarmarg, Kathmandu', vibe: 'Nightclub', musicType: 'EDM, Bollywood, Hip-Hop', priceRange: '$$$', bestDays: 'Fri-Sat', description: 'One of Kathmandu\'s premium nightclubs with international DJs and a spacious dance floor.' },
  { id: 'nl24', name: 'Club Deja Vu', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Nightclub', musicType: 'EDM, Bollywood, Hip-Hop', priceRange: '$$$', bestDays: 'Thu-Sat', description: "A Thamel nightclub running to the early hours alongside LOD and Fahrenheit. Nepal's midnight alcohol rule is loosely enforced; verify hours before going." },
  { id: 'nl5', name: 'Golden Gai', country: 'Japan', location: 'Shinjuku, Tokyo', vibe: 'Intimate micro-bars', musicType: 'Varies by bar', priceRange: '$$-$$$', bestDays: 'Any night', description: 'A maze of 200+ tiny bars, each seating 5-10 people. Each bar has a unique theme, from jazz to punk to anime.', mustSee: true, longDescription: 'Shinjuku Golden Gai is a warren of six narrow alleys packed with more than 200 minuscule bars, most seating only a handful of guests. A survivor of post-war Tokyo, each bar has its own theme and regulars — jazz, punk, film, anime — and many charge a small seat/cover fee. Look for places advertising an English welcome; it is one of the most atmospheric drinking districts in the world.' },
  // nl6 (Robot Restaurant) removed — the show permanently closed in 2023; the space now
  // runs Samurai Restaurant, a DAYTIME-only spectacle (13:00-17:30, closed Thu/Sun, 18+), which
  // does not fit a nightlife card. No replacement card added — see the named Tokyo clubs below.
  { id: 'nl7', name: 'Womb', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Super club', musicType: 'Techno, House', priceRange: '$$$', bestDays: 'Fri-Sat', description: 'One of Asia\'s top nightclubs. World-class sound system, international DJs, and four dance floors. NYE: books out early for its countdown party — a strong pick if Shibuya\'s (now cancelled/fenced-off) street countdown was the plan; verify tickets before relying on it.' },
  { id: 'nl17', name: 'Harlem', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Hip-hop institution', musicType: 'Hip-Hop, R&B', priceRange: '$$', bestDays: 'Fri-Sat', description: "Tokyo's best-known hip-hop club, running since 1997. Peak sets land 23:30-01:00; door typically ¥1,000-3,500 with a drink. Verify hours/cover before going." },
  { id: 'nl18', name: 'Club Camelot', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Hip-hop / R&B, young crowd', musicType: 'Hip-Hop, R&B', priceRange: '$$', bestDays: 'Fri-Sat', description: 'Three-floor Shibuya club with a young, hip-hop/R&B-leaning crowd — also runs a ticketed NYE countdown party. Verify hours/cover (and NYE ticket details) before going.' },
  { id: 'nl19', name: 'ATOM Tokyo', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Multi-floor superclub', musicType: 'EDM, House, Hip-Hop', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'A long-running multi-floor Shibuya club with a different genre per floor. Verify hours/cover before going.' },
  { id: 'nl20', name: 'WARP Shinjuku', country: 'Japan', location: 'Kabukicho, Shinjuku, Tokyo', vibe: 'Mega-club', musicType: 'EDM, Hip-Hop', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'A short walk from the Kabukicho hotel zone — a big EDM/hip-hop dance floor. Verify hours/cover before going.' },
  { id: 'nl8', name: 'Bar High Five', country: 'Japan', location: 'Ginza, Tokyo', vibe: 'Cocktail bar', musicType: 'Jazz / Ambient', priceRange: '$$$$', bestDays: 'Any night', description: 'Consistently ranked among the world\'s best bars. Master bartender Hidetsugu Ueno creates bespoke cocktails.', mustSee: true, longDescription: 'Bar High Five is an intimate Ginza cocktail bar led by celebrated bartender Hidetsugu Ueno, long ranked among the world\'s best. There is no fixed cocktail menu — the bartenders craft a drink to your taste from an encyclopaedic knowledge of spirits and classic technique. It is small, refined and popular, so it is worth arriving early or reserving; expect a seating charge in keeping with high-end Ginza bars.' },
  { id: 'nl9', name: 'Roppongi Hills Club Area', country: 'Japan', location: 'Roppongi, Tokyo', vibe: 'International nightlife hub', musicType: 'Mixed', priceRange: '$$$', bestDays: 'Fri-Sat', description: 'Tokyo\'s famous nightlife district with dozens of clubs and bars. Popular with expats and tourists.' },
  { id: 'nl10', name: 'Zoetrope Whisky Bar', country: 'Japan', location: 'Shinjuku, Tokyo', vibe: 'Whisky haven', musicType: 'Jazz', priceRange: '$$$', bestDays: 'Any night', description: 'Over 200 Japanese whiskies in a tiny, atmospheric bar. Perfect for whisky enthusiasts. Cinema-themed decor.' },

  // — Osaka + Kyoto nightlife (boys-trip route). Legal venues/districts only — no
  // Tobita Shinchi card (red-light district; not a base, not a place to visit). The
  // Soemoncho caution from the source brief is folded into nl13's description below,
  // not given its own card (per the brief's own "Important Planning Boundary").
  { id: 'nl11', name: 'Namba/Dotonbori Nightlife Strip', country: 'Japan', location: 'Namba/Dotonbori, Osaka', vibe: 'Late-night food & bar crawl', musicType: 'Mixed / DJ', priceRange: '$-$$', bestDays: 'Any night', description: 'Osaka\'s main nightlife and food strip along the neon-lit Dotonbori canal — bars, standing izakaya and late-night ramen. Best for a first-night orientation walk and casual bar-hopping; confirm prices before sitting down at any bar with a tout out front.' },
  { id: 'nl12', name: 'Shinsaibashi Club Row', country: 'Japan', location: 'Shinsaibashi, Osaka', vibe: 'Club & bar hopping', musicType: 'EDM, Hip-Hop, Top 40', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'Osaka\'s main club-hopping strip, a short walk from the covered Shinsaibashi-suji arcade — the best base for a bigger party night. Cover charges and any bottle/table minimum vary a lot by door; agree the price before going in.' },
  { id: 'nl13', name: 'Amerikamura Bars', country: 'Japan', location: 'Amerikamura, Osaka', vibe: 'Young, streetwear, hip-hop energy', musicType: 'Hip-Hop, Rap', priceRange: '$-$$', bestDays: 'Any night', description: '"Amemura" is Osaka\'s youth-culture quarter — streetwear shops by day, casual hip-hop and rap-leaning bars by night; a relaxed, less touristy alternative to Shinsaibashi\'s bigger clubs. Note: neighbouring Soemoncho, right next to Dotonbori, is an adult-nightlife-adjacent strip with unclear pricing and persistent touts — treat it as a walk-through, not a place to stop for a drink.' },
  { id: 'nl21', name: 'Club Bambi', country: 'Japan', location: 'Shinsaibashi, Osaka', vibe: 'Young, cheap, hip-hop-inclusive', musicType: 'Hip-Hop, Top 40', priceRange: '$-$$', bestDays: 'Fri-Sat', description: 'A young, budget-friendly Shinsaibashi club with a hip-hop-inclusive floor. Verify hours/cover before going.' },
  { id: 'nl22', name: 'GHOST Ultra Lounge', country: 'Japan', location: 'Shinsaibashi, Osaka', vibe: 'Ultra lounge', musicType: 'EDM, Hip-Hop', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'A Shinsaibashi ultra-lounge club with a bigger production feel than most of the strip. Verify hours/cover before going.' },
  { id: 'nl23', name: 'Pure Osaka', country: 'Japan', location: 'Dotonbori, Osaka', vibe: 'Club', musicType: 'EDM, Hip-Hop, Top 40', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'A Dotonbori-area club, a good rotation pick off the busier Shinsaibashi row. Verify hours/cover before going.' },
  { id: 'nl14', name: 'Kiyamachi-dori', country: 'Japan', location: 'Kiyamachi-dori, Kyoto', vibe: 'Main drinking street', musicType: 'Mixed', priceRange: '$-$$$', bestDays: 'Any night', description: 'Kyoto\'s main nightlife and drinking street, running along the old Takase canal — bars, izakaya and a few small late-night spots packed along a few blocks. The easiest base for a Kyoto night out, an easy walk from Kawaramachi.' },
  { id: 'nl15', name: 'Pontocho Alley Bars', country: 'Japan', location: 'Pontocho, Kyoto', vibe: 'Traditional alley bars & restaurants', musicType: 'Mixed / Ambient', priceRange: '$$-$$$$', bestDays: 'Any night', description: 'A narrow, lantern-lit alley between the Kamo River and Kiyamachi lined with traditional restaurants and intimate bars. Best for an atmospheric night walk and dinner rather than club-style partying.', mustSee: true, longDescription: 'Pontocho is one of Kyoto\'s most photographed nightlife lanes — a single narrow alley of wooden machiya buildings strung with lanterns, running parallel to the Kamo River between Shijo and Sanjo. Some of its traditional restaurants and bars carry a seating charge or are effectively members-only, so look for an English-friendly sign or a posted menu before sitting down; the riverside terraces (yuka) in warmer months are the classic view, but the lane itself is atmospheric year-round.' },
  { id: 'nl16', name: 'Gion Evening Nightlife', country: 'Japan', location: 'Gion, Kyoto', vibe: 'Traditional, upscale atmosphere', musicType: 'Ambient / Traditional', priceRange: '$$$-$$$$', bestDays: 'Any night', description: 'Kyoto\'s famous geisha district by day, and a quieter, more upscale nightlife pocket by evening — traditional bars sit alongside lantern-lit lanes like Hanamikoji. Good for an atmospheric night walk after dinner; most of the exclusive ochaya venues here are introduction-only, so plan on the public bars and the scenery.' },
];
