export interface NightlifeVenue {
  id: string;
  name: string;
  country: 'Nepal' | 'Japan';
  location: string;
  vibe: string;
  musicType: string;
  priceRange: string;
  bestDays: string;
  description: string;
  // --- optional enrichment ---
  /** Curated genuine highlight — drives the "Must-see" badge. */
  mustSee?: boolean;
  /** Longer, accurate description shown in the detail sheet. Real facts only. */
  longDescription?: string;
}

export const NIGHTLIFE_VENUES: NightlifeVenue[] = [
  { id: 'nl1', name: 'Purple Haze Rock Bar', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Rock & live music', musicType: 'Rock, Blues, Indie', priceRange: '$$', bestDays: 'Fri-Sat', description: 'Kathmandu\'s legendary live music venue. Local and international bands perform nightly in an intimate setting.', mustSee: true, longDescription: 'Purple Haze is one of Kathmandu\'s best-known live-music bars, a large multi-level venue in the heart of Thamel that hosts local and touring rock, blues and indie bands most nights. Named after the Hendrix track, it draws a mixed crowd of travellers and locals and gets loud and lively at weekends — arrive early for a spot near the stage.' },
  { id: 'nl2', name: 'Sam\'s Bar', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Backpacker social hub', musicType: 'Mixed / DJ', priceRange: '$', bestDays: 'Every night', description: 'The most famous bar in Thamel. Pool tables, cheap drinks, and a melting pot of travelers from around the world.' },
  { id: 'nl3', name: 'LOD (Lord of the Drinks)', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Upscale lounge', musicType: 'House, Electronic', priceRange: '$$$', bestDays: 'Thu-Sat', description: 'Multi-level upscale lounge with rooftop terrace. Premium cocktails and modern ambiance.' },
  { id: 'nl4', name: 'Club Fahrenheit', country: 'Nepal', location: 'Durbarmarg, Kathmandu', vibe: 'Nightclub', musicType: 'EDM, Bollywood, Hip-Hop', priceRange: '$$$', bestDays: 'Fri-Sat', description: 'One of Kathmandu\'s premium nightclubs with international DJs and a spacious dance floor.' },
  { id: 'nl24', name: 'Club Deja Vu', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Nightclub', musicType: 'EDM, Bollywood, Hip-Hop', priceRange: '$$$', bestDays: 'Thu-Sat', description: "A Thamel nightclub running to the early hours alongside LOD and Fahrenheit. Nepal's midnight alcohol rule is loosely enforced; verify hours before going." },
  // Nepal roster expansion (5 -> 13 venues)
  { id: 'nl25', name: 'Club OMG', country: 'Nepal', location: 'Paryatan Marg, Thamel', vibe: 'Nightclub / dance floor', musicType: 'EDM, Bollywood, Hip-Hop', priceRange: '$$', bestDays: 'Fri-Sat, nightly otherwise', description: 'Dance floor and DJ sets on the floor beneath Purple Haze — an easy same-building pivot from live music to dancing. Free entry for women most nights. Verify current hours before going.' },
  { id: 'nl26', name: 'Prive Nepal', country: 'Nepal', location: 'Soaltee Crowne Plaza, Tahachal', vibe: 'Upscale club', musicType: 'House, EDM', priceRange: '$$$', bestDays: 'Wed, Fri, Sat only', description: 'Upscale club inside the Soaltee Crowne Plaza with international DJ bookings — the most polished production on the Kathmandu club circuit. Open Wed, Fri and Sat only, 23:00-04:00. Verify current lineup/hours before going.' },
  { id: 'nl27', name: 'Casino Royale', country: 'Nepal', location: 'Hotel Yak & Yeti, Durbar Marg', vibe: 'Casino', musicType: 'Ambient', priceRange: 'Free entry (stakes vary)', bestDays: 'Every night (24/7)', description: "Kathmandu's best-known casino, in the century-old Yak & Yeti palace building — table games and slot machines, open 24/7, free entry for foreign passport holders (Nepali citizens are barred by law). Bring a passport; closed-toe shoes required, no shorts or flip-flops." },
  { id: 'nl28', name: "Fat Monk's Rooftop Bar", country: 'Nepal', location: 'Narsingh Chowk Marg, Thamel', vibe: 'Rooftop cocktail bar', musicType: 'Live music, Mixed', priceRange: '$$', bestDays: 'Any night', description: "Widely cited as Thamel's best cocktail program, on a rooftop over Thamel Chowk with live music — a step up from a beer-and-pool bar without going full club. Verify hours before going." },
  { id: 'nl29', name: 'House of Music', country: 'Nepal', location: 'Thamel, Kathmandu', vibe: 'Live music bar', musicType: 'Rock, Jazz, Fusion, Blues', priceRange: '$$', bestDays: 'Nightly', description: "Thamel's most consistent live-music calendar — rock, jazz, fusion and blues nightly. A genuine second live-music night without repeating Purple Haze. Verify current calendar before going." },
  { id: 'nl30', name: 'Shisha Lounge & Bar', country: 'Nepal', location: 'Chaksibari Marg, Thamel', vibe: 'Hookah lounge', musicType: 'Live music sets', priceRange: '$$', bestDays: 'Nightly', description: 'Established 2006, one of Thamel\'s best-known hookah lounges, with two live-music sets a night (20:00-22:00, then 22:30-00:30). Open 12:00-01:00. Verify current live-music schedule before going.' },
  { id: 'nl31', name: 'Mazaaj Hookah Lounge', country: 'Nepal', location: 'Thamel, Kathmandu (rooftop)', vibe: 'Rooftop hookah lounge', musicType: 'Ambient / Live music', priceRange: '$$', bestDays: 'Any night', description: "Claims Thamel's highest rooftop position — warm, low-lit hookah lounge with live music, good for winding a night down without ending it. Verify hours before going." },
  { id: 'nl32', name: 'Fire and Ice', country: 'Nepal', location: 'Tridevi Marg, Thamel', vibe: '24-hour rooftop pizzeria', musicType: 'N/A', priceRange: '$$', bestDays: 'Every night (24h)', description: '24-hour rooftop pizza spot — the standard after-club food stop across Thamel nightlife guides. Genuinely open around the clock, the obvious 1-2am landing spot after any club night.' },
  { id: 'nl5', name: 'Golden Gai', country: 'Japan', location: 'Shinjuku, Tokyo', vibe: 'Intimate micro-bars', musicType: 'Varies by bar', priceRange: '$$-$$$', bestDays: 'Any night', description: 'A maze of 200+ tiny bars, each seating 5-10 people. Each bar has a unique theme, from jazz to punk to anime.', mustSee: true, longDescription: 'Shinjuku Golden Gai is a warren of six narrow alleys packed with more than 200 minuscule bars, most seating only a handful of guests. A survivor of post-war Tokyo, each bar has its own theme and regulars — jazz, punk, film, anime — and many charge a small seat/cover fee. Look for places advertising an English welcome; it is one of the most atmospheric drinking districts in the world.' },
  // nl6 (Robot Restaurant) removed — the show permanently closed in 2023; the space now
  // runs Samurai Restaurant, a DAYTIME-only spectacle (13:00-17:30, closed Thu/Sun, 18+), which
  // does not fit a nightlife card. No replacement card added — see the named Tokyo clubs below.
  { id: 'nl7', name: 'Womb', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Super club', musicType: 'Techno, House', priceRange: '$$$', bestDays: 'Fri-Sat', description: 'One of Asia\'s top nightclubs. World-class sound system, international DJs, and four dance floors. NYE: books out early for its countdown party — a strong pick if Shibuya\'s (now cancelled/fenced-off) street countdown was the plan; verify tickets before relying on it.' },
  { id: 'nl17', name: 'Harlem', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Hip-hop institution', musicType: 'Hip-Hop, R&B', priceRange: '$$', bestDays: 'Fri-Sat', description: "Tokyo's best-known hip-hop club, running since 1997. Peak sets land 23:30-01:00; door typically ¥1,000-3,500 with a drink. Verify hours/cover before going." },
  { id: 'nl18', name: 'Club Camelot', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Hip-hop / R&B, young crowd', musicType: 'Hip-Hop, R&B', priceRange: '$$', bestDays: 'Fri-Sat', description: 'Three-floor Shibuya club with a young, hip-hop/R&B-leaning crowd — also runs a ticketed NYE countdown party. Verify hours/cover (and NYE ticket details) before going.' },
  { id: 'nl19', name: 'ATOM Tokyo', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Multi-floor superclub', musicType: 'EDM, House, Hip-Hop', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'A long-running multi-floor Shibuya club with a different genre per floor. Verify hours/cover before going.' },
  { id: 'nl20', name: 'WARP Shinjuku', country: 'Japan', location: 'Kabukicho, Shinjuku, Tokyo', vibe: 'Mega-club', musicType: 'EDM, Hip-Hop', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'A short walk from the Kabukicho hotel zone — a big EDM/hip-hop dance floor. Verify hours/cover before going.' },
  { id: 'nl8', name: 'Bar High Five', country: 'Japan', location: 'Ginza, Tokyo', vibe: 'Cocktail bar', musicType: 'Jazz / Ambient', priceRange: '$$$$', bestDays: 'Any night', description: 'Consistently ranked among the world\'s best bars. Master bartender Hidetsugu Ueno creates bespoke cocktails.', mustSee: true, longDescription: 'Bar High Five is an intimate Ginza cocktail bar led by celebrated bartender Hidetsugu Ueno, long ranked among the world\'s best. There is no fixed cocktail menu — the bartenders craft a drink to your taste from an encyclopaedic knowledge of spirits and classic technique. It is small, refined and popular, so it is worth arriving early or reserving; expect a seating charge in keeping with high-end Ginza bars.' },
  { id: 'nl9', name: 'Roppongi Hills Club Area', country: 'Japan', location: 'Roppongi, Tokyo', vibe: 'International nightlife hub', musicType: 'Mixed', priceRange: '$$$', bestDays: 'Fri-Sat', description: 'Tokyo\'s famous nightlife district with dozens of clubs and bars. Popular with expats and tourists.' },
  { id: 'nl10', name: 'Zoetrope Whisky Bar', country: 'Japan', location: 'Shinjuku, Tokyo', vibe: 'Whisky haven', musicType: 'Jazz', priceRange: '$$$', bestDays: 'Any night', description: 'Over 200 Japanese whiskies in a tiny, atmospheric bar. Perfect for whisky enthusiasts. Cinema-themed decor.' },

  // — Osaka + Kyoto nightlife (boys-trip route). Legal venues/districts only — no
  // Tobita Shinchi card (red-light district; not a base, not a place to visit). The
  // Soemoncho caution from the source brief is folded into nl13's description below,
  // not given its own card (per the brief's own "Important Planning Boundary").
  { id: 'nl11', name: 'Namba/Dotonbori Nightlife Strip', country: 'Japan', location: 'Namba/Dotonbori, Osaka', vibe: 'Late-night food & bar crawl', musicType: 'Mixed / DJ', priceRange: '$-$$', bestDays: 'Any night', description: 'Osaka\'s main nightlife and food strip along the neon-lit Dotonbori canal — bars, standing izakaya and late-night ramen. Best for a first-night orientation walk and casual bar-hopping; confirm prices before sitting down at any bar with a tout out front.' },
  { id: 'nl12', name: 'Shinsaibashi Club Row', country: 'Japan', location: 'Shinsaibashi, Osaka', vibe: 'Club & bar hopping', musicType: 'EDM, Hip-Hop, Top 40', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'Osaka\'s main club-hopping strip, a short walk from the covered Shinsaibashi-suji arcade — the best base for a bigger party night. Cover charges and any bottle/table minimum vary a lot by door; agree the price before going in.' },
  { id: 'nl13', name: 'Amerikamura Bars', country: 'Japan', location: 'Amerikamura, Osaka', vibe: 'Young, streetwear, hip-hop energy', musicType: 'Hip-Hop, Rap', priceRange: '$-$$', bestDays: 'Any night', description: '"Amemura" is Osaka\'s youth-culture quarter — streetwear shops by day, casual hip-hop and rap-leaning bars by night; a relaxed, less touristy alternative to Shinsaibashi\'s bigger clubs. Note: neighbouring Soemoncho, right next to Dotonbori, is an adult-nightlife-adjacent strip with unclear pricing and persistent touts — treat it as a walk-through, not a place to stop for a drink.' },
  { id: 'nl21', name: 'Club Bambi', country: 'Japan', location: 'Shinsaibashi, Osaka', vibe: 'Young, cheap, hip-hop-inclusive', musicType: 'Hip-Hop, Top 40', priceRange: '$-$$', bestDays: 'Fri-Sat', description: 'A young, budget-friendly Shinsaibashi club with a hip-hop-inclusive floor. Verify hours/cover before going.' },
  { id: 'nl22', name: 'GHOST Ultra Lounge', country: 'Japan', location: 'Shinsaibashi, Osaka', vibe: 'Ultra lounge', musicType: 'EDM, Hip-Hop', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'A Shinsaibashi ultra-lounge club with a bigger production feel than most of the strip. Verify hours/cover before going.' },
  { id: 'nl23', name: 'Pure Osaka', country: 'Japan', location: 'Dotonbori, Osaka', vibe: 'Club', musicType: 'EDM, Hip-Hop, Top 40', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'A Dotonbori-area club, a good rotation pick off the busier Shinsaibashi row. Verify hours/cover before going.' },
  { id: 'nl14', name: 'Kiyamachi-dori', country: 'Japan', location: 'Kiyamachi-dori, Kyoto', vibe: 'Main drinking street', musicType: 'Mixed', priceRange: '$-$$$', bestDays: 'Any night', description: 'Kyoto\'s main nightlife and drinking street, running along the old Takase canal — bars, izakaya and a few small late-night spots packed along a few blocks. The easiest base for a Kyoto night out, an easy walk from Kawaramachi.' },
  { id: 'nl15', name: 'Pontocho Alley Bars', country: 'Japan', location: 'Pontocho, Kyoto', vibe: 'Traditional alley bars & restaurants', musicType: 'Mixed / Ambient', priceRange: '$$-$$$$', bestDays: 'Any night', description: 'A narrow, lantern-lit alley between the Kamo River and Kiyamachi lined with traditional restaurants and intimate bars. Best for an atmospheric night walk and dinner rather than club-style partying.', mustSee: true, longDescription: 'Pontocho is one of Kyoto\'s most photographed nightlife lanes — a single narrow alley of wooden machiya buildings strung with lanterns, running parallel to the Kamo River between Shijo and Sanjo. Some of its traditional restaurants and bars carry a seating charge or are effectively members-only, so look for an English-friendly sign or a posted menu before sitting down; the riverside terraces (yuka) in warmer months are the classic view, but the lane itself is atmospheric year-round.' },
  { id: 'nl16', name: 'Gion Evening Nightlife', country: 'Japan', location: 'Gion, Kyoto', vibe: 'Traditional, upscale atmosphere', musicType: 'Ambient / Traditional', priceRange: '$$$-$$$$', bestDays: 'Any night', description: 'Kyoto\'s famous geisha district by day, and a quieter, more upscale nightlife pocket by evening — traditional bars sit alongside lantern-lit lanes like Hanamikoji. Good for an atmospheric night walk after dinner; most of the exclusive ochaya venues here are introduction-only, so plan on the public bars and the scenery.' },

  // Japan roster expansion (18 -> 52 Japan venues).
  // Breadth pass, not gap-filling — avoid list (ageHa, Sound Museum Vision, Contact) confirmed
  // permanently closed and deliberately excluded.
  { id: 'nl33', name: 'TK Shibuya', country: 'Japan', location: 'Udagawa-cho, Shibuya, Tokyo', vibe: 'Largest single-floor club in Shibuya', musicType: 'Top 40, Hip-Hop, House', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: "Shibuya's largest single-floor club (~1,000 cap), open-format top 40/hip-hop/house — an easy alternative to the Harlem/Camelot rotation. Verify cover/hours before going." },
  { id: 'nl34', name: 'T2 Shinjuku', country: 'Japan', location: 'Kabukicho, Shinjuku, Tokyo', vibe: 'Big-room club, open all week', musicType: 'Open-format', priceRange: '$$-$$$', bestDays: 'Any night, biggest Fri-Sat', description: "TK Shibuya's sister club in Kabukicho — a big room open all week, useful for weeknight dates when WARP feels repetitive. Verify before going." },
  { id: 'nl35', name: 'Sel Octagon', country: 'Japan', location: 'Roppongi, Tokyo', vibe: 'EDM-festival-production club', musicType: 'EDM', priceRange: '$$$', bestDays: 'Fri-Sat', description: "Roppongi's EDM-festival-production anchor club — the closest thing to a big-room EDM night in the itinerary. Verify before going." },
  { id: 'nl36', name: 'Odeon Tokyo', country: 'Japan', location: 'Roppongi, Tokyo', vibe: 'Resident/international DJ club', musicType: 'House, Hip-Hop', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: '10+ years running with strong resident/international DJ bookings — a step up from the tout-heavy Roppongi strip bars. Verify before going.' },
  { id: 'nl37', name: 'Circus Tokyo', country: 'Japan', location: 'Shibuya, Tokyo', vibe: 'Underground techno/house room', musicType: 'Techno, House', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'Underground techno/house room in Shibuya, smaller and more serious than WOMB. Verify current hours/status before going.' },
  { id: 'nl38', name: 'Zero Tokyo', country: 'Japan', location: 'Kabukicho, Shinjuku, Tokyo', vibe: 'Club', musicType: 'Open-format', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: "Another Kabukicho-area club to rotate against WARP so Shinjuku nights aren't always the same room. Verify before going." },
  { id: 'nl39', name: '1OAK Tokyo', country: 'Japan', location: 'Azabu-Juban, Tokyo', vibe: 'Upscale international lounge/club', musicType: 'Hip-Hop, House', priceRange: '$$$$', bestDays: 'Fri-Sat', description: 'Upscale international lounge/club chain outpost — a good option for a dressier night. Verify before going.' },
  { id: 'nl40', name: 'Karaoke Kan (Shibuya)', country: 'Japan', location: 'Udagawa-cho, Shibuya, Tokyo', vibe: 'Karaoke box', musicType: 'N/A', priceRange: '$$', bestDays: 'Any night', description: 'The actual karaoke box used in Lost in Translation (rooms 601/602) — genuine bragging-rights stop with private rooms. Good pre-club warm-up or post-club wind-down.' },
  { id: 'nl41', name: 'Big Echo Shibuya Center-Gai', country: 'Japan', location: 'Shibuya Center-Gai, Tokyo', vibe: '24h karaoke box', musicType: 'N/A', priceRange: '$', bestDays: 'Every night (24h)', description: 'Cheapest, always-open karaoke option — roughly ¥225-1,985 depending on time/day. The reliable fallback when everything else is shut, e.g. New Year\'s Day.' },
  { id: 'nl42', name: 'Tasuichi', country: 'Japan', location: 'Shibuya backstreets, Tokyo', vibe: 'Standing bar', musicType: 'N/A', priceRange: '$', bestDays: 'Any night', description: 'Well-known Shibuya standing bar, popular with locals and foreigners alike — cheap beer and highballs. A casual pre-game stop.' },
  { id: 'nl43', name: 'Shibuya Tachinomi Cluster', country: 'Japan', location: 'Shibuya Station east exit backstreets, Tokyo', vibe: 'Standing-bar cluster', musicType: 'N/A', priceRange: '$', bestDays: 'Any night', description: "Narrow standing-room counters around Shibuya's east side — beer from ¥200, highballs from ¥300. Genuine local drinking culture, not a tourist trap." },
  { id: 'nl44', name: 'CÉ LA VI Tokyo', country: 'Japan', location: 'Shibuya (rooftop), Tokyo', vibe: 'Upscale rooftop lounge/club', musicType: 'House, Lounge', priceRange: '$$$$', bestDays: 'Fri-Sat', description: 'Upscale rooftop lounge/club — a higher-production option for a dressier night, alongside WOMB/Circus in current Shibuya guides. Verify hours/cover before going.' },
  { id: 'nl45', name: 'DUG Jazz Cafe & Bar', country: 'Japan', location: 'Near Shinjuku Station east exit, Tokyo', vibe: 'Jazz kissa', musicType: 'Jazz', priceRange: '$$', bestDays: 'Any night', description: '60-year-old jazz kissa and a Murakami-novel setting (Norwegian Wood) — a genuine Tokyo institution, an easy add-on to a Golden Gai night.' },
  { id: 'nl46', name: 'Whiska', country: 'Japan', location: 'Shinjuku Golden Gai, Tokyo', vibe: 'Whisky bar', musicType: 'Jazz (recorded)', priceRange: '$$-$$$', bestDays: 'Any night', description: "Whisky bar with a jazz-CD soundtrack twist — a Golden Gai stop that isn't Zoetrope." },
  { id: 'nl47', name: 'Bar Shinjuku Whisky Salon', country: 'Japan', location: 'Adjacent to Golden Gai, Shinjuku, Tokyo', vibe: 'Whisky bar', musicType: 'Ambient', priceRange: '$$$', bestDays: 'Any night', description: 'Flagship bar of "Master of Whisky" Kazunori Shizuya — a quieter respite bar right next to the alley crawl.' },
  { id: 'nl48', name: 'Fuunji', country: 'Japan', location: 'Shinjuku, Tokyo', vibe: 'Tsukemen ramen shop', musicType: 'N/A', priceRange: '$', bestDays: 'Evenings only', description: "Famous tsukemen (dipping ramen) — evening-only, so it's a pre-club anchor rather than a 3am one. Worth naming as the before-you-go-out ramen stop." },
  { id: 'nl49', name: 'Round1 (Ikebukuro/Odaiba)', country: 'Japan', location: 'Ikebukuro / Odaiba, Tokyo', vibe: '24h bowling/karaoke/arcade complex', musicType: 'N/A', priceRange: '$$', bestDays: 'Every night (24h)', description: 'A genuine 24h bowling/karaoke/arcade complex — the honest answer for "what do we do at 3am that isn\'t another bar" on a lighter night.' },
  { id: 'nl50', name: 'Vampire Cafe', country: 'Japan', location: 'Ginza (7th floor), Tokyo', vibe: 'Gothic-themed bar', musicType: 'Ambient', priceRange: '$$-$$$', bestDays: 'Evenings (closes ~midnight)', description: "Gothic-themed bar with coffin tables and staff in vampire costume — one of Tokyo's longest-running themed bars. A novelty pre-club stop, not a headliner." },
  { id: 'nl51', name: 'Ninja Akasaka', country: 'Japan', location: 'Akasaka, Tokyo', vibe: 'Interactive ninja-themed dining', musicType: 'N/A', priceRange: '$$$', bestDays: 'Reserve ahead', description: 'Interactive ninja-themed dining and entertainment, confirmed operating in 2026. Reserve ahead — dinner-hour activity.' },
  { id: 'nl52', name: 'Alice in Fantasy Book', country: 'Japan', location: 'Shinjuku, Tokyo', vibe: 'Alice in Wonderland-themed bar', musicType: 'N/A', priceRange: '$$-$$$', bestDays: 'Any night', description: 'Alice in Wonderland-themed restaurant/bar — a novelty pre-game stop.' },
  { id: 'nl53', name: 'Kagaya', country: 'Japan', location: 'Hatanodai, Tokyo', vibe: 'Surreal themed restaurant', musicType: 'N/A', priceRange: '$$-$$$', bestDays: 'Reserve ahead', description: "Tokyo's most surreal themed restaurant — frog costumes, puppets and audience-participation chaos. A cult favorite worth the detour once; reserve ahead, it's small and popular." },
  { id: 'nl54', name: 'Club Joule', country: 'Japan', location: 'Shinsaibashi, Osaka', vibe: '3-floor flagship club', musicType: 'EDM, Hip-Hop', priceRange: '¥2,000-3,000 (incl. drinks)', bestDays: 'Fri-Sat', description: '3-floor flagship club — 800-cap main floor, mezzanine, VIP level, rooftop terrace; EDM to hip-hop with international DJs. Verify before going.' },
  { id: 'nl55', name: 'AMMONA', country: 'Japan', location: 'Shinsaibashi, Osaka', vibe: 'Dressier club', musicType: 'House, EDM', priceRange: '¥2,500-3,500', bestDays: 'Fri-Sat', description: 'Dressier Shinsaibashi option — high ceilings, chandeliers, events run to morning, well-turned-out crowd. Verify before going.' },
  { id: 'nl56', name: 'Giraffe', country: 'Japan', location: 'Dotonbori (steps from the Glico sign), Osaka', vibe: 'Unpretentious party club', musicType: 'Top 40, Hip-Hop', priceRange: '$-$$', bestDays: 'Any night', description: 'Unpretentious, party-first club steps from the Glico sign — mixed tourist/local crowd, a safe easy first-night pick. Verify before going.' },
  { id: 'nl57', name: 'Gala Resort', country: 'Japan', location: 'Shinsaibashi area, Osaka', vibe: 'Club', musicType: 'Hip-Hop, House', priceRange: '$$-$$$', bestDays: 'Fri-Sat', description: 'Strong hip-hop/house focus with staff used to international guests. Verify before going.' },
  { id: 'nl58', name: 'Big Echo/Karaoke Kan (Namba/Shinsaibashi)', country: 'Japan', location: 'Namba/Shinsaibashi, Osaka', vibe: 'Karaoke box', musicType: 'N/A', priceRange: '$-$$', bestDays: 'Any night', description: 'Same reliable karaoke chains as Tokyo, branches in Namba and Shinsaibashi — a cheap, always-open fallback.' },
  { id: 'nl59', name: 'Hozenji Yokocho', country: 'Japan', location: 'Behind Hozenji Temple, near Namba Station, Osaka', vibe: 'Historic lantern-lit alley', musicType: 'N/A', priceRange: '$-$$', bestDays: 'Early-to-mid evening', description: 'Lantern-lit 17th-century stone alley with ~60 bars/izakaya/kushikatsu shops — genuinely atmospheric. Most spots close ~22:00-23:00, so treat as a pre-club dinner/drinks stop, not a late-night one.' },
  { id: 'nl60', name: 'Nihonshu Unagidani', country: 'Japan', location: 'Near Shinsaibashi Station, Osaka', vibe: 'Standing sake bar', musicType: 'N/A', priceRange: '$', bestDays: 'Any night, early-to-mid evening', description: 'Standing sake bar with 100+ varieties in eye-catching fridges — a genuine local-culture detour off the club strip.' },
  { id: 'nl61', name: 'Rooftop Bar OO', country: 'Japan', location: 'Osaka (rooftop)', vibe: 'Rooftop lounge', musicType: 'House, Lounge', priceRange: '$$$', bestDays: 'Any night', description: 'Pool, DJ sets and atmospheric lighting — a lounge alternative before or between club stops. Verify before going.' },
  { id: 'nl62', name: 'Rocking Bar ING', country: 'Japan', location: 'Kiyamachi-dori, Kyoto', vibe: 'Dive rock bar', musicType: 'Rock', priceRange: '$-$$', bestDays: 'Any night', description: 'Dive rock-and-roll bar run by the same owner (Mr. Hako) for 20+ years, Rolling Stones-obsessed decor — the anti-Pontocho counterpoint on Kiyamachi-dori.' },
  { id: 'nl63', name: 'Rokudenashi', country: 'Japan', location: 'Kiyamachi, Kyoto (2F, 127 Saitocho, Shimogyo Ward)', vibe: 'Jazz bar', musicType: 'Jazz', priceRange: '$$', bestDays: 'Any night', description: 'Jazz bar run by a working jazz drummer, open ~40 years — a genuine Kyoto underground-jazz institution.' },
  { id: 'nl64', name: 'Sent James Club', country: 'Japan', location: 'Pontocho, Kyoto', vibe: 'Riverside jazz bar', musicType: 'Jazz', priceRange: '$$-$$$', bestDays: 'Any night', description: 'Running since 1983, riverside terrace, mellow jazz — the atmospheric-bar pick to pair with a Pontocho dinner.' },
  { id: 'nl65', name: 'HUB Kyoto', country: 'Japan', location: 'Kiyamachi-dori, Kyoto', vibe: 'British pub franchise', musicType: 'Mixed', priceRange: '$', bestDays: 'Any night', description: 'British pub franchise on Kiyamachi-dori — casual, expat-friendly, an easy standing-bar option for something less traditional.' },
  { id: 'nl66', name: 'Urbanguild', country: 'Japan', location: 'Kiyamachi-dori, Kyoto', vibe: 'Small performance space', musicType: 'Jazz to experimental electronic', priceRange: '$-$$', bestDays: 'Check calendar', description: 'Eclectic small performance space, jazz to experimental electronic — a different-flavor stop for one of the three Kyoto nights. Check the calendar; programming varies by night.' },
];
