export interface PhotoSpot {
  id: string;
  name: string;
  country: 'Nepal' | 'Japan';
  city: string;
  bestTime: string;
  style: string;
  gear: string;
  tip: string;
  category: string;
  image?: string;
  // --- optional enrichment ---
  /** Curated genuine highlight — drives the "Must-see" badge. */
  mustSee?: boolean;
  /** Longer, accurate description shown in the detail sheet. Real facts only. */
  longDescription?: string;
}

export const PHOTO_SPOTS: PhotoSpot[] = [
  { id: 'ps1', image: '/images/photography/ps1.jpg', name: 'Nagarkot Himalayan Panorama', country: 'Nepal', city: 'Nagarkot', bestTime: 'Sunrise (6:00-7:00 AM)', style: 'Landscape', gear: 'Telephoto 70-200mm, tripod', tip: 'Arrive 30 min before sunrise. Shoot through blue hour into golden hour.', category: 'Sunrise', mustSee: true, longDescription: 'From the Nagarkot ridge east of Kathmandu, a clear winter dawn reveals a long arc of Himalayan peaks turning gold as the sun rises. A telephoto lens compresses the distant ranges into layered ridgelines, while a tripod lets you shoot through blue hour into golden hour. December typically offers the cleanest, driest skies of the year for this classic panorama.' },
  { id: 'ps2', image: '/images/photography/ps2.jpg', name: 'Swayambhunath Valley View', country: 'Nepal', city: 'Kathmandu', bestTime: 'Sunrise', style: 'Cityscape / Landscape', gear: 'Wide-angle 16-35mm', tip: 'Climb to the top of the stupa for 360° valley panorama.', category: 'Sunrise' },
  { id: 'ps3', image: '/images/photography/ps3.jpg', name: 'Boudhanath Golden Hour', country: 'Nepal', city: 'Kathmandu', bestTime: 'Sunset (4:30-5:30 PM)', style: 'Architecture / Street', gear: '35mm or 50mm prime', tip: 'Shoot from rooftop cafes for elevated perspective of the stupa.', category: 'Sunset', mustSee: true, longDescription: 'At golden hour the great white dome of Boudhanath glows warm and pilgrims begin their evening kora (clockwise circuit), lighting butter lamps as the light fades. A fast prime is ideal for candid portraits and the flutter of prayer flags; the rooftop cafes ringing the stupa give an elevated angle that takes in the painted Buddha eyes and the circling crowd below.' },
  { id: 'ps4', image: '/images/photography/ps4.jpg', name: 'Shibuya Crossing from Above', country: 'Japan', city: 'Tokyo', bestTime: 'Blue hour (5:00-6:00 PM)', style: 'Urban / Street', gear: 'Wide-angle, fast lens f/1.8', tip: 'Shibuya Sky deck for the ultimate aerial shot. Long exposure for light trails.', category: 'Night', mustSee: true, longDescription: 'The world\'s busiest pedestrian scramble is best photographed from above at blue hour, when the sky still holds colour and the neon and video screens light up. The open-air Shibuya Sky deck gives the definitive aerial; a long exposure turns the crossing crowds and traffic into flowing light. From street level, the Tsutaya Starbucks window offers a classic head-on angle.' },
  { id: 'ps5', image: '/images/photography/ps5.jpg', name: 'Fushimi Inari Torii Gates', country: 'Japan', city: 'Kyoto', bestTime: 'Dawn (6:00-7:00 AM)', style: 'Architecture / Leading Lines', gear: '24-70mm zoom', tip: 'Arrive before 7 AM for empty tunnel shots. Use leading line composition.', category: 'Instagram', mustSee: true, longDescription: 'The Senbon Torii — thousands of vermilion gates forming tunnels up Mt Inari — is one of Japan\'s most photographed subjects. The gates make a natural leading line; a mid-range zoom lets you frame both the tunnel interior and single-gate details. Because the shrine is open 24 hours and free, arriving before 7 AM is the only reliable way to catch the tunnels empty.' },
  { id: 'ps6', image: '/images/photography/ps6.jpg', name: 'Asan Bazaar Street Life', country: 'Nepal', city: 'Kathmandu', bestTime: 'Morning (8:00-10:00 AM)', style: 'Street / Documentary', gear: '35mm or 50mm prime', tip: 'Use a compact setup. Ask permission for portraits. Morning light filters through narrow alleys.', category: 'Street' },
  { id: 'ps7', image: '/images/photography/ps7.jpg', name: 'Kabukicho Neon District', country: 'Japan', city: 'Tokyo', bestTime: 'Night (8:00-11:00 PM)', style: 'Night / Neon', gear: 'Fast prime 35mm f/1.4, high ISO capable body', tip: 'Shoot in rain for reflections on wet streets. Cyberpunk vibes guaranteed.', category: 'Night', mustSee: true, longDescription: 'Kabukicho, Shinjuku\'s dense entertainment quarter, is a wall of neon signs, izakaya lanterns and towering screens that reads like a cyberpunk film set after dark. A fast prime and a high-ISO body handle the low light; shooting on a wet night doubles the neon in street reflections. The Godzilla head peering over the Toho building and the narrow side alleys are reliable compositions.' },
  { id: 'ps8', image: '/images/photography/ps8.jpg', name: 'Golden Pavilion (Kinkaku-ji)', country: 'Japan', city: 'Kyoto', bestTime: 'Morning (9:00 AM)', style: 'Architecture / Reflection', gear: '70-200mm telephoto', tip: 'Mirror reflection in pond is the classic shot. Snow days are rare magic.', category: 'Architecture' },
  { id: 'ps9', image: '/images/photography/ps9.jpg', name: 'Kathmandu Durbar Square Details', country: 'Nepal', city: 'Kathmandu', bestTime: 'Morning', style: 'Architecture / Detail', gear: 'Macro or 100mm', tip: 'Focus on intricate wood carvings and stone sculptures. Side light reveals textures.', category: 'Architecture' },
  { id: 'ps10', image: '/images/photography/ps10.jpg', name: 'Tsukiji Market Food Close-ups', country: 'Japan', city: 'Tokyo', bestTime: 'Morning (7:00-10:00 AM)', style: 'Food Photography', gear: '50mm or 85mm, natural light', tip: 'Shoot the preparation process, not just the final dish. Steam adds atmosphere.', category: 'Food' },
  { id: 'ps11', image: '/images/photography/ps11.jpg', name: 'Arashiyama Bamboo Forest', country: 'Japan', city: 'Kyoto', bestTime: 'Early morning', style: 'Nature / Leading Lines', gear: 'Ultra-wide 14mm', tip: 'Look up for the canopy shot. December illumination adds warm lights.', category: 'Nature' },
  { id: 'ps12', image: '/images/photography/ps12.jpg', name: 'Pashupatinath Aarti Ceremony', country: 'Nepal', city: 'Kathmandu', bestTime: 'Evening aarti', style: 'Cultural / Low Light', gear: 'Fast prime, high ISO', tip: 'Shoot from across the river. Fire and smoke create dramatic atmosphere.', category: 'Cultural' },
  // --- Photography guide expansion: Instagrammable spots, Nepal + Japan ---
  { id: 'ps13', name: 'Bhaktapur Durbar Square / 55-Window Palace', country: 'Nepal', city: 'Bhaktapur', bestTime: 'Golden hour, morning or late afternoon', style: 'Architecture / Heritage', gear: 'Wide-angle for the square, 85-100mm for the carved-window details', tip: 'Arrive before the tour-bus wave hits mid-morning; side light in the golden hours rakes across the wood carving and stone facades.', category: 'Architecture', mustSee: true, longDescription: 'Bhaktapur\'s Durbar Square is the best-preserved of the three Kathmandu Valley royal squares, its pagoda temples and the 55-Window Palace showing off some of Nepal\'s finest Newar wood and stone carving. Arriving before the mid-morning tour-bus wave leaves the square\'s brick-paved plazas nearly empty; golden-hour side light rakes across the carved windows and stone lion guardians, picking out detail flat midday light flattens. A wide-angle frames the temple complex as a whole, while an 85-100mm lens isolates individual carvings on the palace facade.' },
  { id: 'ps14', name: 'Patan Durbar Square Golden-Hour Streets', country: 'Nepal', city: 'Lalitpur (Patan)', bestTime: 'Late afternoon golden hour', style: 'Street / Architecture', gear: '35mm or 50mm prime', tip: 'The narrow lanes around the square catch warm side light late in the day — this is what the itinerary\'s own golden-hour street photography stop in Patan is built for.', category: 'Sunset' },
  { id: 'ps15', name: 'Chandragiri Hills Cable-Car Summit View', country: 'Nepal', city: 'Chandragiri', bestTime: 'Clear morning', style: 'Landscape', gear: 'Telephoto 70-200mm for the distant ridgelines', tip: 'December has the clearest air of the year — on a good day Everest is visible on the horizon from the cable-car summit station.', category: 'Nature' },
  { id: 'ps16', name: 'Garden of Dreams', country: 'Nepal', city: 'Kathmandu', bestTime: 'Midday soft light or golden hour', style: 'Architecture / Garden', gear: '24-70mm', tip: 'Neo-classical pavilions, fountains and manicured lawns — a genuine calm-oasis Instagram spot a block from Thamel.', category: 'Instagram' },
  { id: 'ps17', name: 'Thamel Street Scenes', country: 'Nepal', city: 'Kathmandu', bestTime: 'Evening / blue hour', style: 'Street', gear: '35mm, fast aperture', tip: 'Prayer flags strung over neon shop signs and narrow alleys — shoot the tangle of wires and signage overhead, not just street level.', category: 'Street' },
  { id: 'ps18', name: 'Budhanilkantha (Sleeping Vishnu)', country: 'Nepal', city: 'Budhanilkantha, north Kathmandu', bestTime: 'Late morning', style: 'Cultural', gear: 'Wide-angle for the water tank + statue', tip: 'Nepal\'s largest stone statue — a 5m reclining Vishnu floating in a water tank; shoot low and wide to get the reflection.', category: 'Cultural' },
  { id: 'ps19', name: 'Dotonbori Canal & the Glico Running Man Sign', country: 'Japan', city: 'Osaka', bestTime: 'Night', style: 'Neon / Night', gear: 'Fast prime, tripod for canal reflections', tip: 'Shoot from Ebisu Bridge for the classic Glico-sign-over-the-canal composition; a slow shutter smooths the canal reflections of the neon.', category: 'Night', mustSee: true, longDescription: 'Dotonbori Canal is Osaka\'s neon heart — a narrow waterway lined with towering illuminated signage, the giant mechanical Glico Running Man chief among them since 1935. Ebisu Bridge, directly opposite the sign, gives the classic composition: the runner and its rivals reflected in the canal below. A tripod and a slow shutter smooth the water into a mirror of colour, while a fast prime handles the crowds and low light after dark. The canal is busiest, and brightest, after sunset.' },
  { id: 'ps20', name: 'Osaka Castle & Moat', country: 'Japan', city: 'Osaka', bestTime: 'Clear morning', style: 'Architecture / Landscape', gear: 'Wide-angle for the keep + moat, telephoto for detail', tip: 'Winter\'s bare plum grove keeps the sightlines to the castle open — shoot from across the moat for the reflection.', category: 'Architecture' },
  { id: 'ps21', name: 'Umeda Sky Building — Floating Garden Observatory', country: 'Japan', city: 'Osaka', bestTime: 'Sunset / blue hour', style: 'Cityscape', gear: 'Wide-angle, no tripod (handheld only allowed)', tip: 'Open-air rooftop deck at 173m with a waist-high barrier and nothing overhead — go right at sunset to catch the city lights coming on; confirmed open and operating in 2026.', category: 'Sunset' },
  { id: 'ps22', name: 'Osaka Hikari-Renaissance (Nakanoshima Illumination)', country: 'Japan', city: 'Osaka', bestTime: 'Evening, ~mid-Dec (2025-26 pattern: Dec 14-31)', style: 'Night / Illumination', gear: 'Tripod, wide-angle', tip: 'Projection mapping on the Osaka City Central Public Hall plus a "tunnel of light" on Nakanoshima — a Dec-only seasonal event that overlaps the Osaka leg (Dec 19-23) well; verify exact 2026 dates closer to November.', category: 'Night' },
  { id: 'ps23', name: 'Gion / Hanamikoji Lantern-Lit Lanes', country: 'Japan', city: 'Kyoto', bestTime: 'Early evening', style: 'Street / Cultural', gear: '35mm, fast aperture, no flash', tip: 'Shoot only on the main streets — Hanamikoji, Shirakawa-dori, Sannenzaka. Kyoto enforces a real ¥10,000 fine for photographing on Gion\'s private side-alleys or photographing geiko/maiko without consent; stick to the public streets.', category: 'Street', mustSee: true, longDescription: 'Gion\'s Hanamikoji-dori is Kyoto\'s best-preserved geisha district, its wooden machiya teahouses lit by paper lanterns in early evening. Shoot from the main public streets — Hanamikoji, Shirakawa-dori, Sannenzaka — where the lantern light and latticed facades make the shot on their own. Kyoto now enforces a real ¥10,000 fine for photographing on Gion\'s private side-alleys, and photographing geiko or maiko without consent is off-limits entirely; stick to the public streets rather than chasing a private-lane shot.' },
  { id: 'ps24', name: 'Nishiki Market', country: 'Japan', city: 'Kyoto', bestTime: 'Late morning / midday', style: 'Food / Street', gear: '35-50mm', tip: '"Kyoto\'s Kitchen" — a 400m covered arcade; shoot the vendor stalls and skewered street food close-up, it\'s busiest and most photogenic mid-morning before the lunch rush.', category: 'Food' },
  { id: 'ps25', name: "Philosopher's Path", country: 'Japan', city: 'Kyoto', bestTime: 'Late morning, soft light', style: 'Nature', gear: '50mm', tip: 'Honest caveat: this is famous for spring cherry blossoms, which won\'t be present in December — winter gives a quieter, bare-branch canal walk instead, photogenic in a different, calmer register. Not currently a separate itinerary stop; easiest tacked onto the Kiyomizu-dera/Higashiyama day if there\'s flex time.', category: 'Nature' },
  { id: 'ps26', name: 'Nara Park (Deer + Tōdai-ji)', country: 'Japan', city: 'Nara', bestTime: 'Midday', style: 'Nature / Cultural', gear: '85mm for deer portraits, wide-angle for Tōdai-ji\'s Great Buddha Hall', tip: '~30-45 min one-way from Osaka or Kyoto via Kintetsu Limited Express — genuinely great and easy logistically, but needs its own day-trip slot; none is currently free in the schedule. Flagging as an optional swap-in, not assuming it fits.', category: 'Cultural' },
  { id: 'ps27', name: 'Harajuku — Takeshita-dori', country: 'Japan', city: 'Tokyo', bestTime: 'Midday', style: 'Street', gear: '24-35mm', tip: 'Shoot from the elevated pedestrian bridge nearby for the crowd-density shot down the street.', category: 'Street' },
  { id: 'ps28', name: 'Senso-ji & Nakamise-dori', country: 'Japan', city: 'Tokyo', bestTime: 'Morning, before 9:30am crowds', style: 'Cultural / Architecture', gear: 'Wide-angle for Kaminarimon Gate', tip: 'Tokyo\'s oldest temple — the giant red lantern under Kaminarimon Gate is the single most photographed frame in Asakusa; get there at opening for an empty shot.', category: 'Cultural', mustSee: true, longDescription: 'Senso-ji is Tokyo\'s oldest temple, and the giant red lantern hanging under Kaminarimon Gate is arguably the single most photographed frame in Asakusa. Arrive at opening, before the 9:30 AM crowds arrive, for a rare empty shot straight through the gate and down Nakamise-dori\'s arcade of souvenir stalls to the temple\'s main hall. A wide-angle lens takes in the full lantern and gate together; return at night for a quieter, atmospherically lit version of the same frame.' },
  { id: 'ps29', name: 'Tokyo Tower at Night', country: 'Japan', city: 'Tokyo', bestTime: 'Blue hour / night', style: 'Night / Cityscape', gear: 'Telephoto from a distance, tripod', tip: 'Shoot from Shiba Park or a Roppongi rooftop for the tower lit orange against the skyline; Tokyo Skytree (Sumida/Asakusa side) is the alt if the group is over that way instead.', category: 'Night' },
  { id: 'ps30', name: 'Meiji Shrine Forest', country: 'Japan', city: 'Tokyo', bestTime: 'Morning', style: 'Nature', gear: '35mm', tip: 'A genuinely dense forest inside the city — the gravel approach under the torii gate is the classic shot; the itinerary already marks this stop optional depending on group energy after NYE.', category: 'Nature' },
  { id: 'ps31', name: 'Odaiba Waterfront & Rainbow Bridge', country: 'Japan', city: 'Tokyo', bestTime: 'Blue hour / night', style: 'Night / Cityscape', gear: 'Wide-angle, tripod for the bridge light show', tip: 'Not currently on the itinerary. Real correction: the life-size Unicorn Gundam statue that used to anchor Odaiba\'s DiverCity plaza is being removed at the end of August 2026 — it will be gone before this trip. Shoot the Rainbow Bridge and skyline from the Odaiba waterfront instead, not a Gundam photo.', category: 'Night' },
  { id: 'ps32', name: 'Nakano Broadway', country: 'Japan', city: 'Tokyo', bestTime: 'Afternoon', style: 'Instagram / Street', gear: '24mm', tip: 'The retro multi-floor arcade interior — vintage signage, glass figure cases stacked floor to ceiling; quieter and more photogenic than Akihabara for interior shots.', category: 'Instagram' },
  { id: 'ps33', name: 'Marunouchi Illumination (Naka-dori)', country: 'Japan', city: 'Tokyo', bestTime: 'Evening, ~4pm-11pm (midnight in Dec); season runs ~Nov 13-Feb 15', style: 'Night / Illumination', gear: 'Tripod, wide-angle', tip: '~820,000 champagne-gold LEDs along a 1.2km stretch near Tokyo Station; covers the entire Tokyo leg (Dec 27-Jan 9) — easy to slot into a Ginza/Marunouchi evening.', category: 'Night', mustSee: true, longDescription: 'Naka-dori, the tree-lined avenue running through Tokyo\'s Marunouchi business district, turns into a 1.2km tunnel of roughly 820,000 champagne-gold LEDs each winter — one of Tokyo\'s largest illuminations. The season runs mid-November to mid-February on the established pattern, lit 4 PM-11 PM (until midnight through December), which covers the entire Tokyo leg of the trip (Dec 27-Jan 9). A tripod and wide-angle lens take in the full avenue of lit trees; it\'s an easy add to a Ginza/Marunouchi evening near Tokyo Station.' },
  { id: 'ps34', name: 'Tokyo Midtown "Walkway of Light"', country: 'Japan', city: 'Tokyo', bestTime: 'Evening, 5-11pm; runs through Feb 23', style: 'Night / Illumination', gear: 'Wide-angle, tripod optional', tip: 'Free, walking distance of the existing Tokyo Tower/Roppongi Hills day (matches the itinerary\'s Jan 4 Roppongi stop).', category: 'Night' },
];

export const PHOTO_CATEGORIES = ['All', 'Sunrise', 'Sunset', 'Night', 'Street', 'Architecture', 'Instagram', 'Food', 'Nature', 'Cultural'];
