import { DayPlan } from './trip-data';

export const SAMPLE_ITINERARY: DayPlan[] = [
  {
    date: '2026-12-09',
    city: 'Kathmandu',
    country: 'nepal',
    items: [
      { id: 'n1-1', title: 'Depart Syracuse (SYR)', category: 'transportation', time: '06:00', duration: '2h', notes: 'Early check-in for the first leg; international connection — keep passport & visa docs handy', location: 'Syracuse Hancock Intl (SYR)' },
      { id: 'n1-2', title: 'Connection at Newark / JFK hub', category: 'transportation', time: '08:30', duration: '3h', notes: 'Layover and gate change for the long-haul; grab a meal before boarding', location: 'Newark (EWR) / New York (JFK)' },
      { id: 'n1-3', title: 'Transpacific long-haul leg', category: 'transportation', time: '11:30', duration: '14h', notes: 'Main long-haul flight toward the Gulf/Asia hub; set watch ahead, hydrate, sleep on board', location: 'In transit' },
      { id: 'n1-4', title: 'Overnight layover at Gulf hub', category: 'transportation', time: '23:00', duration: '4h', notes: 'Connection at Doha/Dubai-style hub; stretch, freshen up before the final leg to Kathmandu', location: 'Doha (DOH) / Dubai (DXB)' },
    ],
  },
  {
    date: '2026-12-10',
    city: 'Kathmandu',
    country: 'nepal',
    items: [
      { id: 'n2-1', title: 'Final approach into the Himalayas', category: 'transportation', time: '11:00', duration: '4h', notes: 'Window seat on the left for first glimpses of the snow peaks on descent', location: 'In transit → KTM' },
      { id: 'n2-2', title: 'Land at Tribhuvan International Airport', category: 'transportation', time: '15:00', duration: '1.5h', notes: 'Visa on arrival, baggage claim, currency exchange to Nepali rupees', location: 'Tribhuvan Intl Airport (KTM)' },
      { id: 'n2-3', title: 'Check in to Hotel Yak & Yeti', category: 'hotel', time: '17:00', duration: '1h', notes: 'Heritage wing preferred; rest and freshen up after the long journey', location: 'Durbar Marg, Kathmandu' },
      { id: 'n2-4', title: 'Evening walk in Thamel', category: 'sightseeing', time: '18:30', duration: '1.5h', notes: 'Ease into the city — buy a local SIM card, browse the shops, get oriented', location: 'Thamel' },
      { id: 'n2-5', title: 'Welcome dinner at Bhojan Griha', category: 'food', time: '20:00', duration: '2h', notes: 'Traditional Nepali dal bhat feast in a 150-year-old heritage building with a cultural dance show — reserve ahead', location: 'Dillibazar, Kathmandu' },
    ],
  },
  {
    date: '2026-12-11',
    city: 'Kathmandu',
    country: 'nepal',
    items: [
      { id: 'n3-1', title: 'Sunrise at Swayambhunath (Monkey Temple)', category: 'photography', time: '06:00', duration: '2h', notes: '365 steps to the top for a 360° valley panorama; bring a wide-angle lens for the cityscape', location: 'Swayambhu Hill' },
      { id: 'n3-2', title: 'Breakfast at OR2K Restaurant', category: 'food', time: '08:30', duration: '1h', notes: 'Mediterranean-Nepali fusion with rooftop cushion seating; vegetarian-friendly', location: 'Thamel' },
      { id: 'n3-3', title: 'Kathmandu Durbar Square', category: 'cultural', time: '10:00', duration: '3h', notes: 'UNESCO royal square — Hanuman Dhoka, the temples, and the living goddess at Kumari Ghar', location: 'Basantapur' },
      { id: 'n3-4', title: 'Lunch — momos at Yangling', category: 'food', time: '13:00', duration: '1h', notes: 'Legendary Thamel momo spot; try the jhol (soup) momos', location: 'Thamel' },
      { id: 'n3-5', title: 'Asan Bazaar street photography', category: 'photography', time: '14:30', duration: '2h', notes: 'Oldest market in the city — spices, fabrics and hidden temples; ask permission for portraits', location: 'Asan, Kathmandu' },
      { id: 'n3-6', title: 'Sunset at Boudhanath Stupa', category: 'sightseeing', time: '16:30', duration: '2h', notes: 'Walk clockwise with the pilgrims; shoot the golden-hour dome from a rooftop cafe', location: 'Boudha, Kathmandu' },
    ],
  },
  {
    date: '2026-12-12',
    city: 'Kathmandu',
    country: 'nepal',
    items: [
      { id: 'n4-1', title: 'Morning aarti at Pashupatinath Temple', category: 'cultural', time: '07:00', duration: '2.5h', notes: 'Sacred Hindu temple on the Bagmati; cremation ghats and ritual — photograph with sensitivity (non-Hindus cannot enter the main shrine)', location: 'Pashupatinath' },
      { id: 'n4-2', title: 'Kopan Monastery viewpoint', category: 'photography', time: '10:00', duration: '2h', notes: 'Hilltop monastery overlooking Boudhanath; prayer flags and golden roofs — respect quiet hours', location: 'Kopan Hill, Boudha' },
      { id: 'n4-3', title: 'Lunch at Himalayan Java', category: 'food', time: '12:30', duration: '1h', notes: 'Nepali-grown coffee and a light bite at the garden-view branch', location: 'Boudha, Kathmandu' },
      { id: 'n4-4', title: 'Garden of Dreams', category: 'free', time: '14:30', duration: '2h', notes: 'Neo-classical garden oasis — fountains and pavilions, a calm break from the city bustle', location: 'Kaiser Mahal, Kathmandu' },
      { id: 'n4-5', title: 'Dinner at Roadhouse Cafe', category: 'food', time: '18:30', duration: '1.5h', notes: 'Best wood-fired pizza in town with a craft-beer selection; lively Thamel branch', location: 'Thamel' },
    ],
  },
  {
    date: '2026-12-13',
    city: 'Lalitpur',
    country: 'nepal',
    items: [
      { id: 'n5-1', title: 'Patan Durbar Square', category: 'sightseeing', time: '08:30', duration: '3h', notes: 'The finest Newari architecture — Krishna Temple and the Golden Temple ring the square', location: 'Lalitpur' },
      { id: 'n5-2', title: 'Patan Museum', category: 'cultural', time: '11:30', duration: '1.5h', notes: 'The best museum in Nepal — Hindu & Buddhist bronze and stone art in a restored palace', location: 'Patan' },
      { id: 'n5-3', title: 'Lunch at Cafe Swotha', category: 'food', time: '13:30', duration: '1.5h', notes: 'Newari set meal in a beautifully restored heritage courtyard', location: 'Patan' },
      { id: 'n5-4', title: 'Patan alley courtyards & metalwork', category: 'shopping', time: '15:30', duration: '1.5h', notes: 'Wander the back lanes for hidden bahals and workshops; Patan is famous for handmade bronze and silver', location: 'Patan' },
      { id: 'n5-5', title: 'Golden-hour street photography in Patan', category: 'photography', time: '17:00', duration: '1.5h', notes: 'Warm side light filters through the narrow streets and brick facades', location: 'Patan' },
    ],
  },
  {
    date: '2026-12-14',
    city: 'Nagarkot',
    country: 'nepal',
    items: [
      { id: 'n6-1', title: 'Pre-dawn drive to Nagarkot', category: 'transportation', time: '04:30', duration: '1.5h', notes: 'Early departure to reach the ridge before first light', location: 'Kathmandu → Nagarkot' },
      { id: 'n6-2', title: 'Himalayan sunrise viewpoint', category: 'photography', time: '06:00', duration: '2h', notes: 'Panorama over the Everest, Langtang and Ganesh Himal ranges; telephoto 70-200mm and a tripod essential', location: 'Nagarkot View Tower' },
      { id: 'n6-3', title: 'Mountain breakfast at Club Himalaya', category: 'food', time: '08:30', duration: '1h', notes: 'Relaxed breakfast with the range still in view', location: 'Nagarkot' },
      { id: 'n6-4', title: 'Bhaktapur Durbar Square', category: 'cultural', time: '11:00', duration: '4h', notes: 'Best-preserved medieval city — 55-Window Palace, Nyatapola Temple and the pottery square', location: 'Bhaktapur' },
      { id: 'n6-5', title: 'Juju Dhau (King Curd) tasting', category: 'food', time: '15:00', duration: '30min', notes: 'The famous Bhaktapur sweet yogurt served in a clay pot — a must-try', location: 'Bhaktapur' },
      { id: 'n6-6', title: 'Drive back to Kathmandu', category: 'transportation', time: '16:00', duration: '1.5h', notes: 'Return to the hotel; quiet evening to rest', location: 'Bhaktapur → Kathmandu' },
    ],
  },
  {
    date: '2026-12-15',
    city: 'Kathmandu',
    country: 'nepal',
    items: [
      { id: 'n7-1', title: 'Chandragiri Hills cable car', category: 'nature', time: '08:00', duration: '3.5h', notes: 'Cable car to a hilltop with Himalayan and valley views; December offers the clearest skies — bring layers for the cold at the top', location: 'Chandragiri' },
      { id: 'n7-2', title: 'Summit photography — Everest on a clear day', category: 'photography', time: '11:30', duration: '1h', notes: 'On a clear winter morning the distant peaks line the horizon; telephoto for compressed ridges', location: 'Chandragiri summit' },
      { id: 'n7-3', title: 'Lunch at Thakali Kitchen', category: 'food', time: '13:30', duration: '1h', notes: 'Authentic Thakali dal bhat with unlimited refills — the quintessential Nepali meal', location: 'Kathmandu' },
      { id: 'n7-4', title: 'Budhanilkantha (Sleeping Vishnu)', category: 'cultural', time: '15:00', duration: '1.5h', notes: "Nepal's largest stone statue — a 5-metre reclining Vishnu floating in a water tank", location: 'Budhanilkantha, north Kathmandu' },
      { id: 'n7-5', title: 'Dinner & live music in Thamel', category: 'nightlife', time: '19:00', duration: '2h', notes: 'Wind down with a rooftop dinner and a local band in the tourist quarter', location: 'Thamel' },
    ],
  },
  {
    date: '2026-12-16',
    city: 'Bhaktapur',
    country: 'nepal',
    items: [
      { id: 'n8-1', title: 'Changu Narayan Temple', category: 'cultural', time: '08:00', duration: '2h', notes: 'The oldest Hindu temple in the valley and a UNESCO site — exquisite 5th-century stone and woodcarving', location: 'Changunarayan Hill' },
      { id: 'n8-2', title: 'Hike down toward Bhaktapur', category: 'nature', time: '10:00', duration: '2h', notes: 'Gentle ridge walk through terraced fields with valley views; easy half-day trail', location: 'Changunarayan → Bhaktapur' },
      { id: 'n8-3', title: 'Pottery Square & lunch in Bhaktapur', category: 'food', time: '12:30', duration: '1.5h', notes: 'Watch potters at the wheel, then a Newari lunch in the old town', location: 'Bhaktapur' },
      { id: 'n8-4', title: 'Taudaha Lake birdwatching', category: 'nature', time: '15:30', duration: '1.5h', notes: 'Tranquil lake on the valley rim — December is best for migratory birds; tea stalls along the shore', location: 'Chobhar' },
      { id: 'n8-5', title: 'Quiet dinner near the hotel', category: 'food', time: '19:00', duration: '1.5h', notes: 'Low-key evening to recharge before the final days', location: 'Durbar Marg, Kathmandu' },
    ],
  },
  {
    date: '2026-12-17',
    city: 'Kathmandu',
    country: 'nepal',
    items: [
      { id: 'n9-1', title: 'Pre-dawn climb to Phulchowki', category: 'photography', time: '05:30', duration: '4h', notes: "The valley's highest rim peak, blanketed in rhododendron forest — layered ridge-lines and a Himalayan panorama on clear December mornings", location: 'Phulchowki, Godavari' },
      { id: 'n9-2', title: 'Godavari Botanical Garden', category: 'nature', time: '10:00', duration: '1.5h', notes: 'Peaceful gardens at the foot of Phulchowki — a calm stroll after the climb', location: 'Godavari' },
      { id: 'n9-3', title: 'Lunch back in Patan', category: 'food', time: '13:00', duration: '1h', notes: 'Refuel on the way back into the city', location: 'Patan' },
      { id: 'n9-4', title: 'Chobhar Gorge & Jal Binayak', category: 'sightseeing', time: '15:00', duration: '2h', notes: 'Dramatic gorge where the Bagmati cuts the valley rim; vintage suspension bridge and a riverside temple in soft afternoon light', location: 'Chobhar' },
      { id: 'n9-5', title: 'Farewell dinner at OR2K rooftop', category: 'food', time: '18:30', duration: '1.5h', notes: 'A relaxed last proper Nepal dinner with sunset rooftop views', location: 'Thamel' },
    ],
  },
  {
    date: '2026-12-18',
    city: 'Kathmandu',
    country: 'nepal',
    items: [
      { id: 'n10-1', title: 'Slow breakfast & last city views', category: 'free', time: '08:00', duration: '1.5h', notes: 'No rush this morning — coffee and a final look over the valley', location: 'Kathmandu' },
      { id: 'n10-2', title: 'Souvenir shopping in Thamel & Asan', category: 'shopping', time: '10:00', duration: '2.5h', notes: 'Pashmina, singing bowls, Nepali tea, prayer flags and handmade paper — last gifts before Japan', location: 'Thamel & Asan, Kathmandu' },
      { id: 'n10-3', title: 'Lunch at Cafe Swotha', category: 'food', time: '13:00', duration: '1.5h', notes: 'One more Newari meal in the Patan courtyard', location: 'Patan' },
      { id: 'n10-4', title: 'Garden of Dreams — afternoon unwind', category: 'free', time: '15:00', duration: '1.5h', notes: 'Quiet pavilions and fountains to close out the Nepal leg', location: 'Kaiser Mahal, Kathmandu' },
      { id: 'n10-5', title: 'Pack & confirm tomorrow\'s Japan flight', category: 'hotel', time: '18:00', duration: '1.5h', notes: 'Repack, check in online for the Kathmandu → Tokyo flight, and an early night before the early departure', location: 'Hotel Yak & Yeti, Durbar Marg' },
    ],
  },
  {
    date: '2026-12-19',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j1-1', title: 'Fly from Kathmandu to Tokyo (Narita)', category: 'transportation', time: '08:00', duration: '10h', notes: 'KTM → NRT, likely a one-stop routing; arrive Tokyo in the evening local time. Set watches ahead and fill out the immigration QR via Visit Japan Web before landing', location: 'TIA → Narita Intl (NRT)' },
      { id: 'j1-2', title: 'Narita Express to Shinjuku & check in', category: 'hotel', time: '20:00', duration: '1.5h', notes: 'N\'EX train into the city, then check in to the Shinjuku base hotel; grab IC card (Suica/Pasmo) top-up at the station', location: 'Shinjuku, Tokyo' },
      { id: 'j1-3', title: 'Late-night tsukemen at Fuunji', category: 'food', time: '21:30', duration: '45min', notes: 'Shinjuku\'s legendary dipping ramen — thick fish-based broth and chewy noodles; finish with soup-wari', location: 'Shinjuku, Tokyo' },
      { id: 'j1-4', title: 'Night walk through Kabukicho', category: 'nightlife', time: '22:30', duration: '1h', notes: 'Ease into Tokyo under the neon — Godzilla head, the lantern alleys; a fast prime for cyberpunk reflections on wet streets', location: 'Kabukicho, Shinjuku' },
    ],
  },
  {
    date: '2026-12-20',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j2-1', title: 'Dawn at Senso-ji Temple', category: 'photography', time: '06:30', duration: '2h', notes: 'Tokyo\'s oldest Buddhist temple — shoot the Thunder Gate (Kaminarimon) and the empty Nakamise street before the crowds and shops open', location: 'Asakusa, Tokyo' },
      { id: 'j2-2', title: 'Breakfast & Nakamise-dori snacks', category: 'food', time: '08:30', duration: '1h', notes: 'Melon pan, ningyo-yaki and fresh senbei along the approach as the stalls roll up their shutters', location: 'Asakusa, Tokyo' },
      { id: 'j2-3', title: 'Tokyo Skytree & Sumida views', category: 'sightseeing', time: '10:00', duration: '2h', notes: 'Ride to the Tembo Deck for a clear winter panorama; the Sumida River walk back toward Asakusa frames Skytree and the Asahi building', location: 'Sumida, Tokyo' },
      { id: 'j2-4', title: 'Lunch — conveyor-belt sushi', category: 'food', time: '12:30', duration: '1h', notes: 'Fun, affordable kaiten sushi with touch-screen ordering; Sushiro or Kura are reliable, ¥120-ish a plate', location: 'Asakusa, Tokyo' },
      { id: 'j2-5', title: 'Yanaka Old Town stroll', category: 'cultural', time: '14:30', duration: '2.5h', notes: 'A rare survivor of old Tokyo — narrow lanes, wooden houses and the nostalgic Yanaka Ginza shopping street; crisp winter light makes it glow', location: 'Yanaka, Tokyo' },
      { id: 'j2-6', title: 'Izakaya dinner at Omoide Yokocho', category: 'food', time: '18:30', duration: '2h', notes: '"Memory Lane" — lantern-lit yakitori stalls under the Shinjuku tracks; steam off the grills on a cold night is pure Tokyo. Cash only', location: 'Shinjuku, Tokyo' },
    ],
  },
  {
    date: '2026-12-21',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j3-1', title: 'Morning calm at Meiji Shrine', category: 'cultural', time: '08:00', duration: '1.5h', notes: 'A serene Shinto shrine in a forest in the heart of the city; write a wish on an ema plaque before the day warms up', location: 'Harajuku, Tokyo' },
      { id: 'j3-2', title: 'Takeshita & Omotesando, Harajuku', category: 'shopping', time: '10:00', duration: '2h', notes: 'Youth-fashion chaos on Takeshita-dori then the tree-lined luxury of Omotesando; rainbow cotton candy and crepes for the photos', location: 'Harajuku, Tokyo' },
      { id: 'j3-3', title: 'Lunch — Gyukatsu Motomura', category: 'food', time: '12:30', duration: '1h', notes: 'Deep-fried wagyu cutlet you finish on a hot stone at your table; queue early, medium-rare is perfection', location: 'Shibuya, Tokyo' },
      { id: 'j3-4', title: 'Shibuya Sky observation deck', category: 'sightseeing', time: '15:00', duration: '1.5h', notes: 'Open-air rooftop with the best view down onto the Scramble; clearest in winter, time it for the city lighting up', location: 'Shibuya, Tokyo' },
      { id: 'j3-5', title: 'Shibuya Crossing at blue hour', category: 'photography', time: '17:00', duration: '1h', notes: 'The world\'s busiest crossing — up to 3,000 people at once; wide fast lens, long exposure from the deck or the Starbucks window for light trails', location: 'Shibuya, Tokyo' },
      { id: 'j3-6', title: 'Drinks in Golden Gai', category: 'nightlife', time: '20:00', duration: '2h', notes: 'Six tiny alleys of 200+ themed micro-bars, most seating only a handful; look for an English-friendly sign and expect a small cover', location: 'Shinjuku, Tokyo' },
    ],
  },
  {
    date: '2026-12-22',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j4-1', title: 'teamLab Borderless digital art', category: 'sightseeing', time: '09:30', duration: '3h', notes: 'Immersive museum of ever-changing rooms of light and projection; pre-booked timed ticket, wear white/light colours for the best effect', location: 'Azabudai Hills, Tokyo' },
      { id: 'j4-2', title: 'Lunch in Azabudai Hills', category: 'food', time: '13:00', duration: '1h', notes: 'Casual bite in the new Azabudai food hall before crossing town', location: 'Azabudai, Tokyo' },
      { id: 'j4-3', title: 'Tokyo Tower afternoon climb', category: 'sightseeing', time: '14:30', duration: '1.5h', notes: '333m landmark; the top deck is worth the extra fee and winter air gives the clearest views over the city', location: 'Minato, Tokyo' },
      { id: 'j4-4', title: 'Roppongi Hills Keyakizaka illumination', category: 'photography', time: '17:00', duration: '1.5h', notes: 'A 400m avenue of zelkova trees in blue-and-white "Snow & Blue" LEDs framing Tokyo Tower — central Tokyo\'s iconic December shot', location: 'Roppongi, Tokyo' },
      { id: 'j4-5', title: 'Dinner in Roppongi', category: 'food', time: '19:00', duration: '1.5h', notes: 'Relaxed dinner near the lights before heading back to Shinjuku', location: 'Roppongi, Tokyo' },
    ],
  },
  {
    date: '2026-12-23',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j5-1', title: 'Akihabara Electric Town', category: 'sightseeing', time: '10:00', duration: '2.5h', notes: 'Tokyo\'s electronics and anime paradise — multi-floor arcades, manga shops and figure stores; Super Potato for retro games', location: 'Akihabara, Tokyo' },
      { id: 'j5-2', title: 'GiGO arcade & gachapon', category: 'free', time: '12:30', duration: '1.5h', notes: 'Floors of UFO-catchers, rhythm games and retro cabinets; bring a stack of 100-yen coins — a warm refuge on a cold day', location: 'Akihabara, Tokyo' },
      { id: 'j5-3', title: 'Lunch at a themed maid/anime cafe', category: 'food', time: '14:00', duration: '1h', notes: 'Quintessential Akiba experience; otherwise grab a quick curry between the figure shops', location: 'Akihabara, Tokyo' },
      { id: 'j5-4', title: 'Nakano Broadway collectors\' run', category: 'shopping', time: '15:30', duration: '2h', notes: 'Retro multi-floor mall — the original Mandarake, vintage manga, cels and rare figures; quieter than Akihabara. Basement dessert at Daily Chiko', location: 'Nakano, Tokyo' },
      { id: 'j5-5', title: 'Ramen dinner at Ichiran', category: 'food', time: '18:30', duration: '45min', notes: 'Solo-booth tonkotsu ramen; order barikata (extra firm) noodles and a kaedama refill', location: 'Shinjuku, Tokyo' },
    ],
  },
  {
    date: '2026-12-24',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j6-1', title: 'Tsukiji Outer Market food crawl', category: 'food', time: '08:00', duration: '2.5h', notes: 'Come hungry — fresh uni, fatty tuna sushi, tamagoyaki on a stick and grilled scallops; shoot the prep and the steam, not just the dish', location: 'Tsukiji, Tokyo' },
      { id: 'j6-2', title: 'Hamarikyu Gardens & matcha', category: 'nature', time: '11:00', duration: '1.5h', notes: 'Edo-era seaside garden with skyscrapers behind the pines; a bowl of matcha and a wagashi at the teahouse on the pond', location: 'Chuo, Tokyo' },
      { id: 'j6-3', title: 'Ginza holiday window shopping', category: 'shopping', time: '13:30', duration: '2.5h', notes: 'Tokyo\'s most upscale quarter — Ginza Six, the flagship stores and spectacular December window displays; weekends the avenue goes car-free', location: 'Ginza, Tokyo' },
      { id: 'j6-4', title: 'Christmas Eve illuminations at Marunouchi', category: 'photography', time: '17:00', duration: '1.5h', notes: 'Champagne-gold light tunnels along the Marunouchi avenues by Tokyo Station; Christmas Eve is peak romance-light season in Japan', location: 'Marunouchi, Tokyo' },
      { id: 'j6-5', title: 'Christmas Eve dinner', category: 'food', time: '19:00', duration: '2h', notes: 'A booked special dinner — KFC and strawberry shortcake is the funny Japanese tradition, but a nicer reservation works too', location: 'Marunouchi, Tokyo' },
    ],
  },
  {
    date: '2026-12-25',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j7-1', title: 'Coffee & vintage in Shimokitazawa', category: 'free', time: '09:30', duration: '3h', notes: 'Bohemian low-rise neighbourhood of vintage stores, indie record shops and third-wave coffee; great for thrifting a warm winter coat with no fixed plan', location: 'Shimokitazawa, Tokyo' },
      { id: 'j7-2', title: 'Lunch in Shimokitazawa', category: 'food', time: '12:30', duration: '1h', notes: 'Tiny curry or soup spot among the back lanes', location: 'Shimokitazawa, Tokyo' },
      { id: 'j7-3', title: 'Pokémon Center Mega Tokyo', category: 'shopping', time: '14:30', duration: '1h', notes: 'Flagship store in Sunshine City — exclusive plush and holiday/New Year limited-edition merch that appears in late December', location: 'Ikebukuro, Tokyo' },
      { id: 'j7-4', title: 'Repack & laundry afternoon', category: 'hotel', time: '16:00', duration: '1.5h', notes: 'Light overnight bag for the Hakone onsen leg; leave the big case at the Shinjuku hotel or send ahead via takkyubin', location: 'Shinjuku, Tokyo' },
      { id: 'j7-5', title: 'Yakitori dinner at a local izakaya', category: 'food', time: '18:30', duration: '1.5h', notes: 'Charcoal skewers, a cold beer and the day\'s plan over the counter', location: 'Shinjuku, Tokyo' },
    ],
  },
  {
    date: '2026-12-26',
    city: 'Hakone',
    country: 'japan',
    items: [
      { id: 'j8-1', title: 'Romancecar to Hakone', category: 'transportation', time: '09:00', duration: '1.5h', notes: 'Odakyu Romancecar from Shinjuku to Hakone-Yumoto; pick up a Hakone Free Pass for the loop transport', location: 'Shinjuku → Hakone-Yumoto' },
      { id: 'j8-2', title: 'Hakone loop — ropeway & Owakudani', category: 'nature', time: '11:00', duration: '3h', notes: 'Switchback train, cable car and ropeway over the volcanic Owakudani valley; black eggs boiled in the sulphur springs, Mt Fuji on a clear day', location: 'Owakudani, Hakone' },
      { id: 'j8-3', title: 'Hakone Open-Air Museum', category: 'sightseeing', time: '14:30', duration: '1.5h', notes: 'Sculpture park set against the winter mountains, with a Picasso pavilion and a warm foot-bath fed by hot-spring water', location: 'Ninotaira, Hakone' },
      { id: 'j8-4', title: 'Check in to an onsen ryokan', category: 'hotel', time: '16:30', duration: '1h', notes: 'Tatami room, yukata and a private rotenburo; the classic Japanese cold-weather ritual', location: 'Hakone, Kanagawa' },
      { id: 'j8-5', title: 'Open-air onsen at dusk', category: 'free', time: '17:30', duration: '1h', notes: 'A steaming outdoor bath in the cold December air, often with a view toward Fuji — the quintessential winter experience', location: 'Hakone, Kanagawa' },
      { id: 'j8-6', title: 'Kaiseki dinner at the ryokan', category: 'food', time: '19:00', duration: '2h', notes: 'Multi-course seasonal kaiseki served in-room or in the dining hall; local Ashigara beef and winter vegetables', location: 'Hakone, Kanagawa' },
    ],
  },
  {
    date: '2026-12-27',
    city: 'Kyoto',
    country: 'japan',
    items: [
      { id: 'j9-1', title: 'Sunrise soak & ryokan breakfast', category: 'free', time: '07:00', duration: '1.5h', notes: 'One more morning bath, then a traditional Japanese breakfast of grilled fish, rice and miso before checking out', location: 'Hakone, Kanagawa' },
      { id: 'j9-2', title: 'Lake Ashi pirate cruise & Hakone Shrine', category: 'photography', time: '09:00', duration: '2h', notes: 'Cross Lake Ashi by boat to the lakeside torii gate of Hakone Shrine; Mt Fuji over the water on a clear winter morning is the signature shot', location: 'Moto-Hakone' },
      { id: 'j9-3', title: 'Hakone → Odawara → Kyoto by shinkansen', category: 'transportation', time: '12:00', duration: '3h', notes: 'Bus/train down to Odawara, then the Tokaido Shinkansen (Hikari) to Kyoto; reserve seats on the right for a Mt Fuji glimpse', location: 'Odawara → Kyoto' },
      { id: 'j9-4', title: 'Check in & Gion evening walk', category: 'hotel', time: '15:30', duration: '1.5h', notes: 'Drop bags at the Kyoto hotel, then stroll the lantern-lit lanes of Gion and Hanamikoji as they light up', location: 'Gion, Kyoto' },
      { id: 'j9-5', title: 'Pontocho alley dinner', category: 'food', time: '18:30', duration: '2h', notes: 'Narrow riverside lane of traditional restaurants; obanzai (Kyoto home cooking) or yudofu hot-pot to warm up', location: 'Pontocho, Kyoto' },
    ],
  },
  {
    date: '2026-12-28',
    city: 'Kyoto',
    country: 'japan',
    items: [
      { id: 'j10-1', title: 'Dawn at Fushimi Inari', category: 'photography', time: '06:30', duration: '2.5h', notes: 'Thousands of vermillion torii winding up the mountain; arrive before 7 AM for empty tunnel shots, use the gates as leading lines', location: 'Fushimi, Kyoto' },
      { id: 'j10-2', title: 'Inari-style breakfast & tea', category: 'food', time: '09:30', duration: '1h', notes: 'Kitsune udon and inari-zushi at a shrine-approach stall after the climb', location: 'Fushimi, Kyoto' },
      { id: 'j10-3', title: 'Kinkaku-ji (Golden Pavilion)', category: 'cultural', time: '11:30', duration: '1.5h', notes: 'Gold-leaf Zen temple mirrored in its pond; the classic reflection shot with a telephoto — a dusting of snow here is rare magic', location: 'Kita, Kyoto' },
      { id: 'j10-4', title: 'Matcha parfait at Tsujiri', category: 'food', time: '13:30', duration: '45min', notes: 'Premium Uji matcha in a layered parfait — rich and bitter-sweet; a warm cup of usucha alongside', location: 'Kyoto' },
      { id: 'j10-5', title: 'Nishiki Market & Teramachi', category: 'shopping', time: '15:00', duration: '2h', notes: '"Kyoto\'s Kitchen" — five covered blocks of pickles, knives, yuba and sweets; spills into the Teramachi/Shinkyogoku arcades', location: 'Nakagyo, Kyoto' },
      { id: 'j10-6', title: 'Dinner near Kawaramachi', category: 'food', time: '18:30', duration: '1.5h', notes: 'Kyoto-style ramen or a casual teppan dinner downtown', location: 'Kawaramachi, Kyoto' },
    ],
  },
  {
    date: '2026-12-29',
    city: 'Kyoto',
    country: 'japan',
    items: [
      { id: 'j11-1', title: 'Early Arashiyama Bamboo Grove', category: 'photography', time: '07:00', duration: '1.5h', notes: 'Walk the towering bamboo path before the crowds; arrive before 8 AM and look straight up for the canopy shot with an ultra-wide', location: 'Arashiyama, Kyoto' },
      { id: 'j11-2', title: 'Tenryu-ji garden & Togetsukyo Bridge', category: 'nature', time: '08:45', duration: '1.5h', notes: 'Zen garden with borrowed-scenery mountains, then the riverside Togetsukyo Bridge with the winter hills behind', location: 'Arashiyama, Kyoto' },
      { id: 'j11-3', title: 'Lunch — yudofu by the river', category: 'food', time: '11:00', duration: '1h', notes: 'Simmering tofu hot-pot, an Arashiyama winter speciality, beside the Hozu River', location: 'Arashiyama, Kyoto' },
      { id: 'j11-4', title: 'Kiyomizu-dera & Higashiyama lanes', category: 'cultural', time: '13:30', duration: '3h', notes: 'Hilltop temple with its wooden stage over the valley, then the preserved Sannenzaka/Ninenzaka slopes down through Higashiyama', location: 'Higashiyama, Kyoto' },
      { id: 'j11-5', title: 'Kaiseki dinner in Gion', category: 'food', time: '18:30', duration: '2h', notes: 'A refined multi-course Kyoto kaiseki to close out the Kyoto leg; reserve ahead', location: 'Gion, Kyoto' },
    ],
  },
  {
    date: '2026-12-30',
    city: 'Osaka',
    country: 'japan',
    items: [
      { id: 'j12-1', title: 'Kyoto → Osaka by rapid train', category: 'transportation', time: '08:30', duration: '45min', notes: 'Special Rapid to Osaka Station; an easy day trip — bags stay at the Kyoto hotel', location: 'Kyoto → Osaka' },
      { id: 'j12-2', title: 'Osaka Castle & grounds', category: 'sightseeing', time: '09:45', duration: '2h', notes: 'Reconstructed keep with a museum and skyline views; the plum grove and moat are crisp and quiet in winter', location: 'Chuo, Osaka' },
      { id: 'j12-3', title: 'Shinsaibashi & Amerikamura', category: 'shopping', time: '12:30', duration: '2.5h', notes: 'A long covered shopping arcade plus the youth-fashion blocks of Amemura — perfect for a cold day under one roof', location: 'Chuo, Osaka' },
      { id: 'j12-4', title: 'Dotonbori street-food crawl', category: 'food', time: '15:30', duration: '2.5h', notes: 'Takoyaki at Kukuru, okonomiyaki and the giant Glico man; the neon and the canal reflections at night are unmissable', location: 'Namba, Osaka' },
      { id: 'j12-5', title: 'Return to Kyoto', category: 'transportation', time: '20:00', duration: '45min', notes: 'Evening train back; early-ish night before the move to Tokyo and New Year\'s Eve', location: 'Osaka → Kyoto' },
    ],
  },
  {
    date: '2026-12-31',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j13-1', title: 'Kyoto → Tokyo by shinkansen', category: 'transportation', time: '09:30', duration: '2.5h', notes: 'Nozomi/Hikari back to Tokyo; right-side seats for the Mt Fuji view past Shizuoka. Re-check in to the Shinjuku hotel', location: 'Kyoto → Tokyo' },
      { id: 'j13-2', title: 'Check in & Shinjuku lunch', category: 'hotel', time: '12:30', duration: '1.5h', notes: 'Settle back into the Tokyo base and a relaxed lunch before the New Year\'s Eve plans', location: 'Shinjuku, Tokyo' },
      { id: 'j13-3', title: 'Toshikoshi soba dinner', category: 'food', time: '17:30', duration: '1.5h', notes: '"Year-crossing" buckwheat noodles, the traditional New Year\'s Eve meal for a long life; many shops keep it simple tonight', location: 'Shinjuku, Tokyo' },
      { id: 'j13-4', title: 'Joya-no-kane bells at Zojo-ji', category: 'cultural', time: '22:30', duration: '1.5h', notes: 'Temple bells rung 108 times to ring out the old year, with Tokyo Tower glowing behind; balloons and a countdown at midnight', location: 'Shiba, Tokyo' },
      { id: 'j13-5', title: 'New Year countdown', category: 'nightlife', time: '23:45', duration: '1h', notes: 'See in 2027 at the Zojo-ji / Shibuya countdown crowds; trains run all night on New Year\'s Eve', location: 'Tokyo' },
    ],
  },
  {
    date: '2027-01-01',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j14-1', title: 'Hatsumode at Meiji Shrine', category: 'cultural', time: '10:00', duration: '2.5h', notes: 'The first shrine visit of the year — Meiji draws millions over New Year; long but moving queues, omikuji fortunes and hamaya arrows', location: 'Harajuku, Tokyo' },
      { id: 'j14-2', title: 'New Year osechi & ozoni lunch', category: 'food', time: '13:00', duration: '1.5h', notes: 'Traditional New Year foods — lacquered-box osechi and ozoni mochi soup; note many shops shut on Jan 1, so book or rely on hotels/konbini', location: 'Harajuku, Tokyo' },
      { id: 'j14-3', title: 'Fukubukuro lucky-bag hunt', category: 'shopping', time: '15:00', duration: '2h', notes: 'New Year "lucky bags" of surprise discounted goods at the department stores that do open — a fun Japanese Jan 1 tradition', location: 'Shinjuku, Tokyo' },
      { id: 'j14-4', title: 'Quiet New Year evening', category: 'free', time: '18:00', duration: '2h', notes: 'A calm first night of the year — onsen-style sento bath or a relaxed hotel dinner as the city rests', location: 'Shinjuku, Tokyo' },
    ],
  },
  {
    date: '2027-01-02',
    city: 'Kawaguchiko',
    country: 'japan',
    items: [
      { id: 'j15-1', title: 'Express bus to Lake Kawaguchiko', category: 'transportation', time: '07:30', duration: '2h', notes: 'Highway bus from Shinjuku to the Fuji Five Lakes; reserve ahead as New Year travel is busy', location: 'Shinjuku → Kawaguchiko' },
      { id: 'j15-2', title: 'Mt Fuji winter reflection', category: 'photography', time: '10:00', duration: '2h', notes: 'Japan\'s icon is clearest in winter — snow-capped peak mirrored in Lake Kawaguchiko; the lakeshore and Oishi Park are the best angles', location: 'Lake Kawaguchiko, Yamanashi' },
      { id: 'j15-3', title: 'Lunch — Yoshida udon', category: 'food', time: '12:30', duration: '1h', notes: 'Thick, chewy local udon, a Fuji-area speciality that warms you through on a cold day', location: 'Fujikawaguchiko, Yamanashi' },
      { id: 'j15-4', title: 'Chureito Pagoda viewpoint', category: 'sightseeing', time: '14:00', duration: '2h', notes: 'Climb ~400 steps to the five-storey pagoda framing Mt Fuji — the most iconic Japan postcard view, even better with winter snow', location: 'Fujiyoshida, Yamanashi' },
      { id: 'j15-5', title: 'Return bus to Tokyo', category: 'transportation', time: '17:00', duration: '2h', notes: 'Evening bus back to Shinjuku; nap on the ride after the cold mountain air', location: 'Kawaguchiko → Shinjuku' },
    ],
  },
  {
    date: '2027-01-03',
    city: 'Yuzawa',
    country: 'japan',
    items: [
      { id: 'j16-1', title: 'Shinkansen to Gala Yuzawa', category: 'transportation', time: '08:00', duration: '1.5h', notes: 'Joetsu Shinkansen straight from Tokyo Station to Gala Yuzawa, whose station connects directly to the gondola — a no-car snow day', location: 'Tokyo → Gala Yuzawa, Niigata' },
      { id: 'j16-2', title: 'Snow play & beginner slopes', category: 'nature', time: '10:00', duration: '4h', notes: 'Guaranteed deep winter snow within a day trip — rent gear on site for the slopes, or stick to the snow-play and sledding area', location: 'Gala Yuzawa, Niigata' },
      { id: 'j16-3', title: 'Mountain-lodge lunch', category: 'food', time: '12:30', duration: '1h', notes: 'Hot curry-rice or ramen in the resort lodge with the snowfields outside the window', location: 'Gala Yuzawa, Niigata' },
      { id: 'j16-4', title: 'Onsen soak before the train', category: 'free', time: '15:00', duration: '1h', notes: 'Resort hot spring to thaw out after the snow; Echigo-Yuzawa is famous onsen and sake country', location: 'Yuzawa, Niigata' },
      { id: 'j16-5', title: 'Shinkansen back to Tokyo', category: 'transportation', time: '17:00', duration: '1.5h', notes: 'Fast train home; grab an ekiben and a local Niigata sake for the ride', location: 'Gala Yuzawa → Tokyo' },
    ],
  },
  {
    date: '2027-01-04',
    city: 'Nikko',
    country: 'japan',
    items: [
      { id: 'j17-1', title: 'Train to Nikko', category: 'transportation', time: '07:30', duration: '2h', notes: 'Tobu line from Asakusa to Nikko; a UNESCO mountain-shrine town, often under fresh snow in early January', location: 'Asakusa → Nikko, Tochigi' },
      { id: 'j17-2', title: 'Toshogu Shrine in the snow', category: 'cultural', time: '10:00', duration: '2.5h', notes: 'Lavishly carved shrine complex of the Tokugawa shoguns — the "see/hear/speak no evil" monkeys and the sleeping cat; cedar forest and snow', location: 'Nikko, Tochigi' },
      { id: 'j17-3', title: 'Shinkyo Bridge & lunch', category: 'food', time: '13:00', duration: '1.5h', notes: 'The vermillion sacred bridge over the Daiya River, then Nikko yuba (tofu skin) cuisine to warm up', location: 'Nikko, Tochigi' },
      { id: 'j17-4', title: 'Kegon Falls viewpoint', category: 'nature', time: '15:00', duration: '1.5h', notes: 'A 97m waterfall plunging off Lake Chuzenji, dramatic with winter ice formations (check road conditions up to Chuzenji)', location: 'Chuzenji, Nikko' },
      { id: 'j17-5', title: 'Return train to Tokyo', category: 'transportation', time: '17:30', duration: '2h', notes: 'Evening train back to Asakusa; quiet dinner near the hotel', location: 'Nikko → Tokyo' },
    ],
  },
  {
    date: '2027-01-05',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j18-1', title: 'Ghibli Museum morning slot', category: 'sightseeing', time: '10:00', duration: '2.5h', notes: 'Whimsical Studio Ghibli museum — original art, the rooftop robot soldier and an exclusive short film; date/time-stamped tickets, book the instant they release. No indoor photos', location: 'Mitaka, Tokyo' },
      { id: 'j18-2', title: 'Inokashira Park & Kichijoji', category: 'nature', time: '13:00', duration: '2h', notes: 'Lakeside park beside the museum, then the easygoing Kichijoji neighbourhood; swan boats and a winter-bare canopy', location: 'Kichijoji, Tokyo' },
      { id: 'j18-3', title: 'Harmonica Yokocho izakaya lunch', category: 'food', time: '15:00', duration: '1h', notes: 'A warren of tiny postwar stalls in Kichijoji; standing-bar snacks and a warming drink', location: 'Kichijoji, Tokyo' },
      { id: 'j18-4', title: 'Shimokitazawa second look', category: 'free', time: '16:30', duration: '1.5h', notes: 'Drift back through the vintage shops and record stores nearby for last finds', location: 'Shimokitazawa, Tokyo' },
      { id: 'j18-5', title: 'Yakiniku dinner', category: 'food', time: '19:00', duration: '1.5h', notes: 'Grill-your-own wagyu to celebrate the back half of the trip', location: 'Shibuya, Tokyo' },
    ],
  },
  {
    date: '2027-01-06',
    city: 'Yokohama',
    country: 'japan',
    items: [
      { id: 'j19-1', title: 'Train to Yokohama', category: 'transportation', time: '09:00', duration: '45min', notes: 'Quick ride south to Japan\'s big port city for an easy day trip', location: 'Tokyo → Yokohama' },
      { id: 'j19-2', title: 'Minato Mirai & Cup Noodles Museum', category: 'sightseeing', time: '10:00', duration: '2.5h', notes: 'Waterfront skyline, the Red Brick Warehouse and the playful Cup Noodles Museum where you design your own', location: 'Minato Mirai, Yokohama' },
      { id: 'j19-3', title: 'Yokohama Chinatown lunch', category: 'food', time: '13:00', duration: '1.5h', notes: 'Japan\'s largest Chinatown — steaming nikuman, xiaolongbao and a riot of gates and lanterns; perfect cold-day eating', location: 'Chinatown, Yokohama' },
      { id: 'j19-4', title: 'Sankeien Garden stroll', category: 'nature', time: '15:00', duration: '1.5h', notes: 'Spacious traditional garden with relocated historic buildings and a three-storey pagoda; early plum blossom and winter quiet', location: 'Naka, Yokohama' },
      { id: 'j19-5', title: 'Harbour-light return', category: 'photography', time: '17:00', duration: '1.5h', notes: 'Cosmo Clock 21 Ferris wheel and the bay lights at blue hour before the train back to Tokyo', location: 'Minato Mirai, Yokohama' },
    ],
  },
  {
    date: '2027-01-07',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j20-1', title: 'Imperial Palace East Gardens', category: 'nature', time: '09:30', duration: '2h', notes: 'Walk the former castle grounds and the Nijubashi bridge view; crisp, open and quiet on a winter morning', location: 'Chiyoda, Tokyo' },
      { id: 'j20-2', title: 'teamLab Planets (water installations)', category: 'sightseeing', time: '12:00', duration: '2h', notes: 'The barefoot, wade-through-water sister venue at Toyosu; a different immersive experience from Borderless — pre-book a slot', location: 'Toyosu, Tokyo' },
      { id: 'j20-3', title: 'Lunch at Toyosu Market', category: 'food', time: '14:00', duration: '1h', notes: 'The successor to Tsukiji\'s inner market — a fresh sushi-don breakfast-for-lunch among the wholesalers', location: 'Toyosu, Tokyo' },
      { id: 'j20-4', title: 'Odaiba bayfront & teamLab views', category: 'sightseeing', time: '15:30', duration: '2h', notes: 'Rainbow Bridge, the bayside boardwalk and the Unicorn Gundam statue lighting up at dusk', location: 'Odaiba, Tokyo' },
      { id: 'j20-5', title: 'Sushi omakase dinner', category: 'food', time: '18:30', duration: '2h', notes: 'A proper counter omakase to mark the trip winding down; reserve ahead', location: 'Ginza, Tokyo' },
    ],
  },
  {
    date: '2027-01-08',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j21-1', title: 'Last-morning shrine visit at Nezu', category: 'cultural', time: '09:00', duration: '1.5h', notes: 'A quiet, beautiful shrine with a mini torii tunnel — a calm, crowd-free last cultural moment in the city', location: 'Bunkyo, Tokyo' },
      { id: 'j21-2', title: 'Souvenir & gift shopping', category: 'shopping', time: '11:00', duration: '2.5h', notes: 'Last gifts — Tokyo Banana, KitKat flavours, stationery at Itoya, ceramics in Kappabashi kitchen-town', location: 'Ginza & Kappabashi, Tokyo' },
      { id: 'j21-3', title: 'Farewell tonkatsu lunch', category: 'food', time: '13:30', duration: '1h', notes: 'A crisp tonkatsu set as a final Tokyo meal', location: 'Shinjuku, Tokyo' },
      { id: 'j21-4', title: 'Pack & ship-ahead logistics', category: 'hotel', time: '15:30', duration: '2h', notes: 'Repack, weigh bags, claim tax-free refunds, and do online check-in for tomorrow\'s flight home', location: 'Shinjuku, Tokyo' },
      { id: 'j21-5', title: 'Last-night izakaya farewell', category: 'nightlife', time: '19:00', duration: '2.5h', notes: 'One last round of yakitori, sake and the Tokyo neon to close out the trip', location: 'Shinjuku, Tokyo' },
    ],
  },
  {
    date: '2027-01-09',
    city: 'Tokyo',
    country: 'japan',
    items: [
      { id: 'j22-1', title: 'Slow final breakfast & checkout', category: 'free', time: '08:00', duration: '1.5h', notes: 'Unhurried last morning, final konbini coffee and a look over the city before heading out', location: 'Shinjuku, Tokyo' },
      { id: 'j22-2', title: 'Narita Express to the airport', category: 'transportation', time: '10:30', duration: '1.5h', notes: 'N\'EX from Shinjuku to Narita; allow extra buffer and aim to be airside ~3h before an international departure', location: 'Shinjuku → Narita Intl (NRT)' },
      { id: 'j22-3', title: 'Last airport shopping & lunch', category: 'food', time: '12:30', duration: '1.5h', notes: 'Final KitKats and bento at Narita; spend the last yen and a proper airport ramen send-off', location: 'Narita Intl (NRT)' },
      { id: 'j22-4', title: 'Fly home from Tokyo', category: 'transportation', time: '15:00', duration: '13h', notes: 'Long-haul flight home — crossing the date line means arriving the same day; the trip ends here', location: 'Narita (NRT) → home' },
    ],
  },
];
